### PR TITLE
[fixes #2175] Documentation misc. typos etc. for RC1 

### LINKED ISSUE #2175: Typos in documentation/`README`/`README.*`
#2176 fixes:
- [x] `README`: Agda version number should be 2.6.4

See branch [documentation](https://github.com/jamesmckinna/agda-stdlib/tree/documentation) where I'm collecting these towards an eventual PR for rc1/rc2...:
- [x] `README`: Missing comma L10 at "Bradley Hardy Joachim Breitner,"
- [x] `Relation.Nullary.Decidable.Core`: corrected reference to `README.Design.Decidability`
- [x] `installation-guide` (thanks @Saransh-cpp !)
- [x] instance arguments discussion in `CHANGELOG`
- [ ] ...
- [ ] documenting the 'how to typecheck `README.agda` question/problem... UPDATED: now going to be handled in a separate PR by @gallais 

Now leaving this issue open, to accumulate any of the other documentation things we might find...?

### PR DESCRIPTION
**Pull request by jamesmckinna**

### CODE REVIEW

**Comment by jamesmckinna** [comment]
I'll remove the `README` list item from the issue? Then this can be merged now as is, I think?

**Comment by MatthewDaggitt** [comment]
Nah, let's merge it now. I have faith that you've found them all :wink: If more occur then it's not a huge imposition to create a new PR.

**Comment by jamesmckinna** [comment]
So the merge queue bot reports "0 checks passed"... is that a good thing, or a bad thing?

**Comment by jamesmckinna** [comment]
So `merge when ready` is now the default merge action... but who/what decides 'ready'?

**Comment by MatthewDaggitt** [comment]
> ... is that a good thing, or a bad thing? Doesn't sound good!?

No it's not, the standard library tests should have been run and passed. Investigating now.

> So merge when ready is now the default merge action... but who/what decides 'ready'?

In this case the merge queue decides when it's ready, i.e. it has been rebased on top of all the commits that might have been merged in since this PR was last merged in master, **and** it has passed the tests (i.e. all status checks passed).

So from the maintainers perspective, just think of this button as "Merge". In theory the only reason it should not get merged in shortly after that (~30 minutes) automatically, is if there was a semantic merge conflict.

**Comment by MatthewDaggitt** [comment]
Last commit fixed the problem. Needed to add the `merge_group` event to the CI to get it trigger.

**Comment by MatthewDaggitt** [comment]
Okay now failing because of an [upstream bug](https://github.com/agda/agda/issues/6927) in Agda. Not revealed in ordinary testing, because apparently our CI cache is somehow keyed to the target branch. The merge queue targets a different branch, and therefore when we add something to the merge queue we are re-building Agda for the first time since the bug was introduced.

The linked issue seems to suggest that bumping GHC works so I'll try merging in https://github.com/agda/agda-stdlib/pull/2142

**Comment by MatthewDaggitt** [comment]
Further detective work on https://github.com/agda/agda-stdlib/pull/2187/files has revealed that the cache wasn't triggering because we weren't setting environment variables properly for when we were neither `master` nor `experimental`. I have switched over to the CI related branch for debugging purposes.

**Pull request merged**
