### PR TITLE
New totality proof for strict lexicographic products of binary relations

### PR DESCRIPTION
**Pull request by MatthewDaggitt**
Added an alternative (non-degenerative) proof for totality in Relation.Binary.Product.StrictLex as well as cleaning up the file somewhat.

The original proof only handles the degenerative case (if the first ordering is total then the second ordering isn't used).

### CODE REVIEW

**Comment by asr** [comment]
Please include the name of the property in the CHANGELOG.

**Comment by MatthewDaggitt** [comment]
@asr Also done!

**Comment by asr** [comment]
Please run `make test` and fix the trailing whitespace issues.

**Comment by MatthewDaggitt** [comment]
Hmm, I'm struggling on this one, apologies. 

When running `make test` I get the error `make: fix-agda-whitespace: Command not found`. Looking at the file HACKAGE in the core Agda repository, it suggests I need to run `make install-fix-agda-whitespace`. However I've had a look around in my .cabal folder where Agda is installed and I can find neither the relevant makefile nor src/fix-agda-whitespace.

Do I need to download something separately?

**Comment by asr** [comment]
The `fix-agda-whitespace` program is in the Agda repository. Please download the repo and run `make install-fix-agda-whitespace`.

**Comment by MatthewDaggitt** [comment]
Thanks for your patience. I've fixed the white-space in this and my other pull-requests.

**Comment by asr** [comment]
> I've fixed the white-space in this and my other pull-requests.

Good.

**Comment by asr** [comment]
Testing...

**Comment by asr** [comment]
I squashed your 3 commits into 1. Thanks for your PR!

**Comment by asr** [comment]
I'll add your name to the README file. Should I use 'Matthew Daggitt' or something else?

**Comment by MatthewDaggitt** [comment]
Matthew Daggitt is fine.

**Comment by asr** [comment]
> On Wed, May 11, 2016 at 4:09 PM, Andrés Sicard-Ramírez <
> notifications@github.com> wrote:
>
> > I'll add your name to the README file.

Done.

**Pull request merged**
