### PR TITLE
Make Cancellative be more consistent in whole library

### PR DESCRIPTION
**Pull request by JacquesCarette**
Part of the work done for Issue #1436 . Making the PR now to get a CI run.

### CODE REVIEW

**Comment by MatthewDaggitt** [comment]
Looks good so far, let us know when it's ready to be reviewed!

**Comment by JacquesCarette** [comment]
@MatthewDaggitt the changes in the PR are incomplete because of the issues that I noted in the comments to #1436 .

My feeling is that we might want to consider this PR as self-contained (once I write something for the CHANGELOG) and then discuss some more what might still need done for increased consistency (if anything).

**Comment by MatthewDaggitt** [comment]
Sounds like a plan!

**Comment by JacquesCarette** [comment]
Thanks hugely for the CHANGELOG. As far as I'm concerned, this PR is now ready to go.

**Pull request merged**
