### PR TITLE
fix whitespace problems before starting new work.

### PR DESCRIPTION
**Pull request by JacquesCarette**
There were whitespace issues on master.

### CODE REVIEW

**Comment by MatthewDaggitt** [comment]
So this is actually a bit complicated. The whitespace problems in `README.Text.Tabular` are actually there by design as that is actually the string that is generated.

To fix this we no longer use `fix-agda-whitespace` but instead use the new `fix-whitespace` program in this [repository](https://github.com/agda/fix-whitespace). See issue #1040 for a discussion.

Equally when we switch to `fix-whitespace` we'll no longer check the CHANGELOG for violations.

**Comment by MatthewDaggitt** [comment]
I should add that to get around this in the mean time, I've simply been running `fix-agda-whitespace` and then commenting out `README.Text.Tabular` and not commiting the changes.

**Comment by gallais** [comment]
> Equally when we switch to fix-whitespace we'll no longer check the CHANGELOG for violations.

If we want to, we can keep doing so. It's a matter of editing the `.yaml` file to
include that file too.

**Comment by JacquesCarette** [comment]
The reason I submitted this is that I had downloaded a completely fresh copy of master and did `make test` and it failed on `fix-agda-whitespace`.

So it seems that the infrastructure in the `Makefile` (and probably the `.yaml` file) have not caught up to the current state of `master`?  Or has `master` jumped the gun?

**Comment by MatthewDaggitt** [comment]
Closed, see #1060

**Pull request closed without merging**
