### PR TITLE
`SigmaPropositional`

### PR DESCRIPTION
**Pull request by bch29**
Thanks for merging `Data.Table`!

`SigmaPropositional` seems like the logical next part to get in shape. I've added a little more to it to flesh it out as a module, and also added the bijection between tables and lists that relies on it.

Something I'm not sure about: should the `HomogenouslyIndexed` bit get its own module under `Relation.Binary`? I'm not sure how useful it is in general but it seems strange having it inside `SigmaPropositional`.

### CODE REVIEW

**Comment by MatthewDaggitt** [comment]
Hi @bch29, sorry the delay in replying.

My main concern about this PR, is the fact that, as you mention in your comments, `OverΣ` is just a special case of `REL` from `Pointwise.Dependant`.  Therefore why not just use `REL` directly?

**Comment by bch29** [comment]
You can't use `REL` when the relation over the second position in the dependent pair is homogeneous. For example,

```agda
open import Relation.Binary.PropositionalEquality

example : Σ ℕ (λ n → Fin n → Fin n) → Σ ℕ (λ n → Fin n → Fin n) → Set
example = OverΣ P._≗_

-- this doesn't work:
--
-- > example = Rel (λ n → Fin n → Fin n) P._≗_
```

That relation can't be defined easily in terms of `Rel` because pointwise function equality only works between functions with the same domain. You could use heterogeneous pointwise function equality, but that's more complicated to work with.

**Comment by MatthewDaggitt** [comment]
> You can't use REL when the relation over the second position in the dependent pair is homogeneous.

Hmm okay, I'll play around with this a bit on Thursday.

> Something I'm not sure about: should the HomogenouslyIndexed bit get its own module under Relation.Binary? I'm not sure how useful it is in general but it seems strange having it inside SigmaPropositional.

You're right, it definitely doesn't belong in `SigmaPropositional`! We just need to find out where it does belong. I'll think about it as well.

**Comment by bch29** [comment]
> the tabulate properties should definitely be added

Maybe as a separate PR?

> the homogeneously indexed relations should definitely be added...

Perhaps they could go in a new module `Relation.Binary.Indexed.Homogeneous`?

> I think the answer is to have a version of `REL` ... that uses the new homogeneously indexed relations

I don't think you could do that without requiring that the first elements of the sum are propositionally equal, whether directly or indirectly (by only providing constructors that force them to be equal).

**Comment by MatthewDaggitt** [comment]
>> the tabulate properties should definitely be added
>
> Maybe as a separate PR?

Sounds good.

> Perhaps` they could go in a new module Relation.Binary.Indexed.Homogeneous?

Also sounds good. Can you open another PR?

>> I think the answer is to have a version of REL ... that uses the new homogeneously indexed relations
>
> I don't think you could do that without requiring that the first elements of the sum are propositionally equal, whether directly or indirectly (by only providing constructors that force them to be equal).

Hmm okay. As you no longer need it in your code, maybe best to leave it be for the moment.

**Comment by MatthewDaggitt** [comment]
Closing this as superseded by #268

**Pull request closed without merging**
