### PR TITLE
Make library work with remodeled sort system

### PR DESCRIPTION
**Pull request by jespercockx**
The remodeled sort system (https://github.com/agda/agda/pull/3042) requires this one small change in the library.

### CODE REVIEW

**Comment by gallais** [comment]
Looks like `sequence` could be made level-polymorphic, couldn't it?

**Comment by MatthewDaggitt** [comment]
> Looks like sequence could be made level-polymorphic, couldn't it?

I'll add it in now.

**Comment by asr** [comment]
Don't forget to push this commit into `experimental`, please.

**Comment by MatthewDaggitt** [comment]
@gallais, what are you using to update experimental at the moment?

Is it?
```
git checkout master
git pull
git checkout experimental
git pull --rebase . master
git push -f
```

If this is the "least worst" option at the moment, then we should update the notes...

**Comment by gallais** [comment]
Yes that's what I do. This way we have `experimental = new_stuf ++ master`.

**Comment by MatthewDaggitt** [comment]
Okay, I'll update the notes.

All done @asr

**Comment by bch29** [comment]
RE updating experimental, isn't this something that Travis can automate or at least check?

**Comment by gallais** [comment]
During the first few iterations we got merge conflicts in the README that needed
to be fixed by hand. I'm not sure whether we'll ever get any other but we may?

**Pull request merged**
