### PR TITLE
added basic operations on rationals

### PR DESCRIPTION
**Pull request by sabry**

### CODE REVIEW

**Comment by gallais** [comment]
Once we have a toplevel definition for each sub-structure in [decTotalOrder](https://github.com/agda/agda-stdlib/blob/fd71f9e63557b9d7d230235d1f05d9aa5bbb5dcd/src/Data/Rational.agda#L297),
I think this will be ready for inclusion.

I'm not sure how usable the library is though: I've tried to prove that
`1/ 3 * 1/ 3 == 1/ 9` and had to kill Agda because it kept computing
without producing any output. :/

**Comment by UlfNorell** [comment]
For reference, the implementation of rationals in agda-prelude computes instantly:

```agda
open import Prelude
open import Numeric.Rational

prf : 1 / 3 * (1 / 3) ≡ (1 / 9 ofType Rational)
prf = refl
```

**Comment by MatthewDaggitt** [comment]
Thanks for the refactoring. I did start on trying to merge this pull request some months ago but got lost down the rabbit hole, and ended up tinkering with GCD etc.

From the sound of it, the whole framework needs some profiling and tinkering with. Perhaps we should leave it till after the 0.15 release in January and then make a concerted effort to come up with something that performs better?

**Comment by MatthewDaggitt** [comment]
Closing as superseded by #380 (wow, this is an old PR!)

**Pull request closed without merging**
