### PR TITLE
Divisibility facts

### PR DESCRIPTION
**Pull request by gallais**
I was having [a bit of fun](https://github.com/gallais/potpourri/blob/846de27674989c78b77e479e35e137417c03341e/agda/papers/fibonacci/Fib.agda) with divisibility so I figured I'd throw in the lemmas
I have found to be missing.

### CODE REVIEW

**Comment by gergoerdi** [comment]
I have some divisibility lemmata in https://github.com/gergoerdi/mod-arith/blob/master/Data/Mod/Lemmas.agda is anyone interested in me moving them to stdlib?

**Comment by andreasabel** [comment]
I suppose so...

**Comment by MatthewDaggitt** [comment]
@gergoerdi  Some of them definitely look like good candidates for inclusion, but I'm a bit snowed under in paper deadlines at the moment. Can I get back to you on these at the start of February?

**Comment by gergoerdi** [comment]
@MatthewDaggitt  I mean, it's code from 2012, so there's no urgency here on my end.

**Comment by MatthewDaggitt** [comment]
@gergoerdi Thanks, I've added some of the properties. Cheers.

**Pull request merged**
