### PR TITLE
Fix typo in raise deprecation message

### PR DESCRIPTION
**Pull request by alexarice**

### CODE REVIEW

**Comment by jamesmckinna** [comment]
Sigh... thanks for the eagle-eyed spot!

**Comment by alexarice** [comment]
Only spotted it because I blindly followed the advice in the deprecation message and it didn't work

**Review by jamesmckinna — APPROVED** [review]
Two things (for maintainers) to note for the future:
* Agda didn't catch this when committed back in 2021 (!) (my first PR, or near enough, so I'm still blushing)
* We need a more robust way of dealing with deprecations? cf. #2224

**Comment by jamesmckinna** [comment]
Thanks again for this and your earlier deprecation bug. Please keep them coming! We've opened a milestone for v2.0-release bug fixes... ;-)

**Pull request merged**
