### PR TITLE
Add a couple of missing equality operators

### PR DESCRIPTION
**Pull request by jespercockx**
I'm not at all sure about the names, so feel free to make a suggestion. I'll write the changelog once we've agreed on the names. Also let me know if there's other similar properties that you'd like to have.

### CODE REVIEW

**Comment by JacquesCarette** [comment]
These have been sorely missing - I've got variants of this all over my libraries. [Yes, I know, I should have submitted them...]

As far as names: these seem as good as any. It's kind of annoying to use `d` as a prefix for dependent (since a lot of the library works the other way around, i.e. the default is dependent and the non-dependent version has a `'`). But I think that for `cong` and `subst`, it makes sense to make an exception!

**Comment by jespercockx** [comment]
I'm glad to hear I'm not the only one who finds them essential from time to time!

**Comment by JacquesCarette** [comment]
Though I also must admit that every time I use one of these, that usually causes me to "think harder" and change my definitions so that I no longer have to use them!

**Comment by jespercockx** [comment]
Sure, but thinking hard is a limited resource :)

**Comment by MatthewDaggitt** [comment]
I'm also happy with the names :+1:

**Comment by MatthewDaggitt** [comment]
Probably time for the CHANGELOG entry!

**Pull request merged**
