### PR TITLE
Data.W and Codata.(Musical.)M using Container

### PR DESCRIPTION
**Pull request by gallais**
Now that the Containers are level polymorphic we can refactor `Data.W` and `Codata.Musical.M`
to use them. Might as well throw in `Codata.M` using sized types and copatterns
at the same time.

### CODE REVIEW

**Comment by andreasabel** [comment]
I wonder whether the change to W can be made more gentle by renaming the constructor to something like `sup'` and keeping `sup` as a pattern synonym.
```agda
pattern sup x f = sup' (x , f)
```
Maybe similar, we could have `W A B = W' (A |> B)`. We'd keep the original syntax of the W-type (which is canonical, an original from MLTT), and just use containers for their implementation.

(Musing: If not for bootstrapping problems, one could also change the Sigma type to `Sigma C` for a `Container` `C`; in the end, a `Container` itself is just an indexed set, only its interpretation makes it a container.  One could object to its use in the definition of W on that ground, however, for W it makes sense since the interpretation function is actually used in the constructor.)

**Comment by gallais** [comment]
`Data.W.Indexed` was already using indexed containers so I assumed the only reason
`Data.W` was taking two arguments instead of a single container was to compensate
the fact that so far a `Container`'s shapes and positions needed to live at the same level.

> W it makes sense since the interpretation function is actually used in the constructor

And we can use container morphisms to describe `map`'s argument concisely!

**Comment by MatthewDaggitt** [comment]
Is this ready to be merged? Or is the conversation ongoing?

**Comment by MatthewDaggitt** [comment]
As it seems everyone's quiet, I'm merging this in. If there are changes decided upon later, then we can always open a new PR.

**Pull request merged**
