### PR TITLE
[ refactor ] Make comparisons over Nat more efficient

### PR DESCRIPTION
**Pull request by mechvel**
Your branch is updated according to «origin/master».

changed:      CHANGELOG.md
changed:      src/Data/Nat/Properties.agda

Thanks to the Agda team! The commit "Fast Nat.Show" is merged to "master".

Now, I have deleted my fork, and create a fork by new -- for the commit of "Fast <-cmp for Nat".
I have pushed it to the repository of GitHub.
Please, consider this commit.

### CODE REVIEW

**Comment by MatthewDaggitt** [comment]
Thanks for the PR. Can I ask what tests you've done on this? It seems to me that this implementation changes the complexity from `O(min(m,n))` to `O(|m-n|)`. This will speed up the case where `m ≈ n` but slow it down where `m >> n` or `n >> m`.

This is because the unary proof generation has simply been moved to the function `m∸n≡0⇒m≤n`.

**Comment by gallais** [comment]
> This is because the unary proof generation has simply been moved

IIRC the point of these refactorings is to decide quickly on which constructor to
use in `Trichotomous`. The proofs themselves are still unary so they will be
expensive to compute no matter what.

If we want cheap proofs too, then we need to define `Trichotomous` for the order
defined in terms of equality and also probably erase the equalities.

**Comment by MatthewDaggitt** [comment]
> IIRC the point of these refactorings is to decide quickly on which constructor to
use in Trichotomous. The proofs themselves are still unary so they will be
expensive to compute no matter what.

Ah, thanks for the explanation! Still getting my head around this efficiency stuff and what does get run and what doesn't.

**Comment by mechvel** [comment]
Matthew wrote
> Can I ask what tests you've done on this? It seems to me that this implementation changes the 
> complexity from O(min(m,n)) to O(|m-n|). This will speed up the case when m ≈ n but slow it down 
> when m >> n or n >> m.
>
> This is because the unary proof generation has simply been moved to the function m∸n≡0⇒m≤n.

1) All arithmetic (``∸,  ≟, ...``) is this function is by built-ins. So that the cost of new  <-cmp    
    computation is about ``2* (cost(built-in  ``∸``)).  
2) If the client function inspects the obtained proof for  ``m < n``  or   ``m > n``,  then, of course,
    this may be "exponentially" expensive.

I have tested it on 
```                           
  let n = read from file,  I tried the input n = 30
       p = 5 ^ n
  in 
  show (<-cmp p p),  show (<-cmp p (suc p)), show (<-cmp p 2), show (<-cmp 2 p)  
where
showTri : ∀ {m n} → Tri (m < n) (m ≡ n) (m > n) → String 
showTri (tri< _ _ _) = "lt"                                                     
showTri (tri≈ _ _ _) = "eq"                                                     
showTri (tri> _ _ _) = "gt"     
```
New ``<-cmp`` prints the result in a moment, while <-cmp of lib-1.0 hangs for long.

**Comment by MatthewDaggitt** [comment]
Okay, now I actually understand what's going on, I've re-implemented **all** comparison operations (not just `<-cmp`) in terms of the builtin boolean comparison `_<ᵇ_`. This is a) much shorter than using the built-in subtraction and b) better preserves the logical ordering in the file.

@mechvel  can you give it a test?

**Comment by mechvel** [comment]
MatthewDaggitt wrote
> Okay, now I actually understand what's going on, I've re-implemented all comparison operations (not > just <-cmp) in terms of the builtin boolean comparison _<ᵇ_. This is a) much shorter than using the 
> built-in subtraction and b) better preserves the logical ordering in the file.

Thank you. This looks like a regular way to fix these features about Nat.

> @mechvel can you give it a test?

I have tested 
```
  let n =  read from file and parse to Nat,   put 50 to file 
       p = 5 ^ n;   x = suc p 
  in
  print the results of   p ≤? x,     x ≤? p,    p ≤? 2,    2 ≤? p,     <-cmp p x,   <-cmp x p
```
-- with skipping the proofs on printing.
It performs and prints in a moment.

1) Only it always warns 
                          "Unit was deprecated in v1.1 ... use T ...", 

while the test program does not contain ``Unit``.
Probably it is somewhere in the master(-fork ?) source.

2) Also I can send you (by email ?) the source of the test program.
It includes parsing Nat from String (which is not in standard lib), 
show for (Dec _) and for Trichotomous.
May be it can serve you as a sample in possible further tests
(though I am not against testing things myself).

**Comment by MatthewDaggitt** [comment]
> Only it always warns
"Unit was deprecated in v1.1 ... use T ...",

Fixed that bug.

> Also I can send you (by email ?) the source of the test program.

Can if you want. I have to confess I've never run an Agda program before...

Merging in now.

**Pull request merged**
