### PR TITLE
Makes `⊥-elim` irrelevant

### LINKED ISSUE #114: Make `⊥-elim` irrelevant in its argument
Currently `⊥-elim` is relevant in it's argument:

```agda
⊥-elim : ∀ {w} {Whatever : Set w} → ⊥ → Whatever
⊥-elim ()
```

Which makes it hard to use an irrelevant `⊥` proof.

However, the relevance is strictly non-necessary and I am currently using a custom defined irrelevant argument version:

```agda
⊥-elim-irr : ∀ {α} {A : Set α} → .⊥ → A
⊥-elim-irr ()
```

Therefore, it would be nice, and without loss of generality, if the standard library version was irrelevant in the `⊥` argument as well.

### PR DESCRIPTION
**Pull request by ahmadsalim**
Fixes #114.

### CODE REVIEW

**Comment by andreasabel** [comment]
This would make sense. However, so far the standard library does not make use of irrelevance.  I am a bit hesitant to change the style of the std-lib in this case.

**Comment by ahmadsalim** [comment]
@andreasabel Thanks for the review.
I did not notice that the standard library was not using irrelevance, and thought it was useful since I heavily use irrelevance myself.
Would you prefer that I close the PR?

**Comment by andreasabel** [comment]
Yes.
One could instead include a module `Irrelevance` with the irrelevant definition of bot-elim.

**Comment by ahmadsalim** [comment]
You mean including `Irrelevance` as a submodule of `Data.Empty` with a different version of `\bot-elim`?

**Comment by andreasabel** [comment]
I meant having `Irrelevance` as a top-level module to collect definitions that use irrelevance.
But we could also have `Data.Empty.Irrelevant` for `\bot-elim`.

**Pull request closed without merging**
