### PR TITLE
Add `Instances` modules for exposing instances to instance search

### PR DESCRIPTION
**Pull request by jespercockx**
This is my attempt to get the discussion around #559 started again. So far I just added new modules containing instance declarations for instances that were already defined but not exposed to instance search. I also restricted myself to _unique_ instances, so there are e.g. no Functor instances for sum and product. In a later stage, we could also try to find out what other instances are missing and implement them.

As you can see, the `Instances` modules are really small and minimalistic, so they should not be too much of a burden to maintain.

### CODE REVIEW

**Comment by gallais** [comment]
IIRC instances named `_` are only in scope in the file they are declared in,
not once imported. Cf. #2498

**Comment by MatthewDaggitt** [comment]
> IIRC instances named _ are only in scope in the file they are declared in,
not once imported. Cf. agda/agda#2498

Additionally giving them names would allow users to select which ones they want to import? (or is that not a feature yet?)

In general though I'm happy with this design. Easy to generalise and out of the way if you don't want to use them. :+1:

**Comment by jespercockx** [comment]
Ok, I added the names so they are actually available in other modules. Importing specific instances is more tricky because instances are added already on the `import` statement, so whether you open the module or not (and whether you hide specific fields or not) does not have any effect on instance search. But with well-designed instances it should never be a problem to have some extra unused instances floating around, so I do not believe this is a big problem.

**Comment by jespercockx** [comment]
Travis says:
```
/home/travis/build/agda/agda-stdlib/src/Data/List/Instances.agda:21,23-56

Cannot instantiate the metavariable _18 to solution

Set (Agda.Primitive.lsuc ℓ) since it contains the variable ℓ

which is not in scope of the metavariable or irrelevant in the metavariable but relevant in the solution

when checking that the expression

λ {M} ⦃ inst ⦄ → monadT {ℓ} {M} inst has type

{M : Agda.Builtin.Unit.⊤ → Agda.Builtin.Unit.⊤ → Set ℓ → Set ℓ}

⦃ inst : Category.Monad.Indexed.RawIMonad M ⦄ →

Category.Monad.Indexed.RawIMonad

(λ _ _ →

   M Agda.Builtin.Unit.⊤.tt Agda.Builtin.Unit.⊤.tt Function.Base.∘′

   Agda.Builtin.List.List)
```
I'm not sure what's wrong though, `make test` goes through fine on my PC.

**Comment by gallais** [comment]
Can you try picking a more recent commit hash in `.travis.yml`? It's here:

https://github.com/agda/agda-stdlib/blob/master/.travis.yml#L51

**Comment by gallais** [comment]
That did it! <3

**Comment by MatthewDaggitt** [comment]
@jespercockx only thing missing is a CHANGELOG entry. Any chance you could the entries to the list of new modules?

**Pull request merged**
