### PR TITLE
The great deprivatisation

### PR DESCRIPTION
**Pull request by MatthewDaggitt**
Moved many useful lemmas and properties in Properties.agda files that were previously in private scope, either explicitly or within records, into public scope.

(Now updated without the previous selectivity commit)

### CODE REVIEW

**Comment by MatthewDaggitt** [comment]
The last commit I think makes it fairly obvious that the current contents of Data.Nat is badly placed. The ordering properties (decTotalOrder) should be in the Properties file. Unfortunately it's not possible to do this due to the dependencies in the PartialOrderReasoning. 


My personal suggestion would be to:

- Move the PartialOrderReasoning to its own file
- Move the DecTotalOrder to Data.Properties

At which point Data.Nat is empty so:

- Move the contents of Data.Nat.Base back into Data.Nat? (I haven't checked whether the dependencies allow this)

Purely cosmetic, but if Data.Nat.Properties.Simple is going to exist, I'd also argue to:

- Move all the simple Relation properties out of Data.Nat.Properties into Data.Nat.Properties.Simple (e.g. anything to do with transitivity, associativity, identities of `_⊔_`, `_≤_` etc.). These are the properties that have just been deprivatised.


Obviously this would be carried out on a seperate pull request. It also would change the imports some what. This could be minimised by having Properties re-export Properties.Simple publicly. 

Hmm this Agda stuff is addictive... I only meant to contribute back a couple of my lemmas!

Thoughts?

**Comment by jmchapman** [comment]
Data.Nat.Properties.Simple was created as a simple fix to exactly problem of useful things being present but private.

If are larger scale reorganisation is happening with the same goal in mind, then I would think that Data.Nat.Properties.Simple should disappear.

**Comment by MatthewDaggitt** [comment]
Yes, that would also make sense. The only possible argument against that might be the sheer size of Data.Nat.Properties as it's definitely already one of the biggest files (I've come across) in the stdlib. It can be a bit tricky to search for the exact lemma you want...

**Comment by gallais** [comment]
FYI, `C-c C-z` allows you to search the definitions in scope by matching on their name ("SUBSTRING") or definition they mention (DEFINITION).

E.g. If `Data.Nat` and `Data.Nat.Properties` are open, `C-c C-z "distrib"  _*_ RET` will yield

    Definitions about "distrib", _*_
      *-distrib-∸ʳ
       : (x y z : ℕ) → (y ∸ z) * x ≡ y * x ∸ z * x

**Comment by MatthewDaggitt** [comment]
@gallais Wow, that's a useful one! That should definitely be added [here](http://agda.readthedocs.io/en/latest/tools/emacs-mode.html) at some point. Okay consider my possible argument retracted.

**Comment by MatthewDaggitt** [comment]
Right, I think I've now got at the vast majority of the annoying properties hidden away. Is there anything anyone thinks I've missed?

Assuming the PR is accepted, is there anything else helpful I can do to speed up the process?

**Comment by MatthewDaggitt** [comment]
I realise this pull request has become a total mess and it's scope has grown a bit large and I can see it would be a bit of nightmare to check. As I've got a spare couple of hours, I'm going to close it and refactor the pull request into multiple, new clean pull requests one for each file so each can be checked and accepted individually!

**Pull request closed without merging**
