### PR TITLE
`Data.Table`

### PR DESCRIPTION
**Pull request by bch29**
As discussed in #211, this adds `Data.Table`, a type of fixed-length vector implemented as a function from `Fin n`.

### CODE REVIEW

**Comment by MatthewDaggitt** [comment]
> I should probably not post this but if we're going to call it Table...

Hmm that example is appealing. In my library I would do that by using my `Matrix` datatype (i.e. Table of tables) which I also plan to add at some point. 
```agda
Matrix : ∀ {a} → Set a → ℕ → ℕ → Set a
Matrix A m n = Fin m → Fin n → A

_ : Matrix ℕ 3 2
_ =  λ { zero                     → λ { zero → 1 ; (suc zero) → 2 ; (suc (suc ())) }
          ; (suc zero)            → λ { zero → 3 ; (suc zero) → 4 ; (suc (suc ())) }
          ; (suc (suc zero))   → λ { zero → 5 ; (suc zero) → 6 ; (suc (suc ())) }
          ; (suc (suc (suc ())))
          }
```
which would end up as much the same thing? 

Do you think we would need higher dimensions? I don't see much demand for them. 

By the way the name `Table` is still open to change if you can come up with anything better!

**Comment by bch29** [comment]
@gallais I think N-dimensional tensors are a /teeny/ bit more complicated than necessary for this use case ;)

@MatthewDaggitt `tabulate` has nice symmetry with `List` and `Vec`'s versions.

```agda
List.tabulate : ∀ {a n} {A : Set a} (f : Fin n → A) → List A
Vec.tabulate : ∀ {n a} {A : Set a} → (Fin n → A) → Vec A n
Table.tabulate : ∀ {n a} {A : Set a} → (Fin n → A) → Table A n
```

**Comment by bch29** [comment]
@gallais Also,

```agda
data Tensor {a} (A : Set a) : List ℕ → Set a where
  baseTensor : Tensor A []
  consTensor : ∀ {dim} {dims} → Table (Tensor A dims) dim → Tensor A (dim ∷ dims)
```

**Comment by bch29** [comment]
I've made it a record and added a few more combinators. The constructor is `tabulate` for now, but I'm still open to being convinced otherwise.

One thing I'm not sure about -- I added a `lookup` to `Data.List` (why did this not exist already?), which breaks backwards compatibility because of potential name clashes. Is this generally a problem we care about?

**Comment by bch29** [comment]
I've moved some of the private functions from #211 to the new `Data.Table.Properties` module, and added a few new combinators. I particularly like

```agda
permute : ∀ {m n a} {A : Set a} → Fin m ↔ Fin n → Table A n → Table A m
```

@MatthewDaggitt @gallais is there anything else that needs to be done to make this mergeable?

**Comment by MatthewDaggitt** [comment]
Okay thanks for your changes. I think it's still a little big in scope though to merge everything in at once though.

All the stuff removed can be dealt with in another pull request, promise! I'm just trying to boil it down to a "pure" table implementation.

Once you implement the following changes then I'll be happy to merge it in:
- Move `swapFin` from `Data.Fin.Properties` to `Data.Fin`, rename it `swap` and provide an explanation of what it does. It should be implemented via pattern matching instead of `if_then_else_`. This will then allow you to delete the `if-dec-true` and `if-dec-false` lemmas.
- Move the `swap-lem₁` and `swap-lem₂` in `Data.Fin.Properties` out of public scope and give them more meaningful names.
- Remove the permutation lemmas from `Data.Fin.Properties` from the PR
- Remove the file `SigmaPropositional` from the PR
- Remove the private module definitions at the top of `Data.Table`
- Move the definitions `foldr` and `foldl` from `Data.Table` to `Data.Table.Base`
- Move the definition `pure` from `Data.Table` to `Data.Table.Base` and rename it `replicate` in line with the function from `List` and `Vec`
- Move all the equality properties at the top of `Data.Table` into `Data.Table.Relation.Equality`
- Move all the private lemmas in `Data.Table` (that do not rely on SigmaPropositional) into `Data.Table.Properties` as well as the proof of isomorphisms with `Vec` and `Table`.
- You seem to have carried out a find and replace for `+` to `|` in the changelog. Please can you fix this.

**Comment by bch29** [comment]
I don't want to leave the git history messy and I'm not sure if there's a way to fix it on this branch, so I'm opening a new pull request.

**Comment by asr** [comment]
> I don't want to leave the git history messy and I'm not sure if there's a way to fix it on this branch, so I'm opening a new pull request

I recently learnt that you don't have to close the PR and open a new one, you can just force- push to your branch.

**Pull request closed without merging**
