### PR TITLE
[ fix #642 ] Fixed precedence levels of `Ring` operations

### LINKED ISSUE #642: fix ``_-_``
In standard library of January 1, 2019, 
``_-_`` is defined  in somewhere in IsGroup, and implemented via inversion.
Inversion has precedence 7, and  ``_-_`` in IsRing (Ring) is brought by renaming from  ``_-_`` of IsGroup. So that it occurs, for example, that the library parses ``x - x* y``  to  ``(x - x) * y``.
The tradition is the folloiwing : 
1) ``_-_`` has the same precedence as ``_+_``, and smaller than ``_*_``,
    so that,  ``x - x* y`` needs to be parsed to  ``x - (x * y)``.
 2) in abstract Group  ``x  ∙ (inverse y)``  is named as  ``x div y`` (division) rather than subtraction.

Probably,  ``_-_`` in IsGroup needs to be renamed to some  appropriate ``div-foo``,
and  ``_-_`` to appear in IsRawRing,  with precedence equal to precedence of  ``_+_``,
and implemented there as   ``x + (- y)``.

?

### PR DESCRIPTION
**Pull request by MatthewDaggitt**
Fixes #642. Squeezing one final PR in. Increasing the precedence doesn't seem to have broken anything in the library. @mechvel could you please check that this fixes your problems and I'll merge it in for v1.0 for the release on Monday.

### CODE REVIEW

**Comment by mechvel** [comment]
> @mechvel could you please check that this fixes your problems and I'll merge it in for v1.0 for 
> the release on Monday.

Please, what is the library version do download?

**Comment by mechvel** [comment]
And how do download it?
Last time I managed to download the current experimental version.
But I wonder how to download v1.0 and whether this is what is needed to download and check.

**Comment by mechvel** [comment]
But this lib is not type-checked by Agda-2.6.0-candidate.
After  
...
> git checkout ring-precedent

I command  > cabal install
and lib-0.18 is installed.
Then I change  $agdaOpt to  
`` ...  -i /home/mechvel/agda/stLib/agda-stdlib/src  -i /home/mechvel/inAgda/bfLib/0.01``
and apply
``     > agda  $agdaOpt Structures.agda``
It reports
```
Checking Structures (/home/mechvel/inAgda/bfLib/0.01/Structures.agda).
...
/home/mechvel/agda/stLib/agda-stdlib/src/Data/Empty.agda:16,1-66
COMPILE pragma not allowed in safe mode.
when scope checking the declaration
  open import Data.Empty hiding (⊥-elim)
```

The experimental lib branch is type-checked by Agda 2.6.0. But there are set different precedences.

**Comment by MatthewDaggitt** [comment]
Hmm you're right. That won't work with Agda 2.6.0.

Actually now I've had some more time to think about it, I'm going to postpone this to v1.1, as I'm not convinced this won't have knock on effects. I also need to have a poke around and decide whether or not to increase the semiring precedences as well...

**Comment by mechvel** [comment]
All right.

**Comment by MatthewDaggitt** [comment]
Actually it's much simpler and and more consistent with the rest of the library just to adjust the precedence of `_-_` down.

**Comment by mwageringel** [comment]
On the other hand, the corresponding operators in the ring solver all have precedence 1 higher, for some reason. This probably does not matter though.

**Comment by MatthewDaggitt** [comment]
> On the other hand, the corresponding operators in the ring solver all have precedence 1 higher, for some reason. This probably does not matter though.

Hmm interesting. nice spot. I think you're right that it doesn't matter though as they don't operate over the same type. Eventually the solver is hopefully going to get an overhaul along the lines of #800 anyway.

**Pull request merged**
