### PR TITLE
Added Data.Permutation

### PR DESCRIPTION
**Pull request by zhyltsovd**

### CODE REVIEW

**Comment by MatthewDaggitt** [comment]
@zhyltsovd thank you for the proposal, and apologies for taking _quite_ so long to get back to you.

This has the potential to be valuable addition to the standard library but as it stands there are a few issues:

- There already exists a formalisation for injective functions in the standard library in `Function.Injective` so your code would need to use the existing `Injective` definition. Obviously this will involve altering your implementation.
- Your `thick` and `thin` functions now exist in the standard library under the names `punchIn` and `punchOut`.

Let me know if you'd like to proceed or not. No worries if not, I understand, after all this time, you may have moved on!

**Comment by zhyltsovd** [comment]
@MatthewDaggitt I would definitely like to proceed. I need some time to update myself with the current state of affairs though.

**Comment by MatthewDaggitt** [comment]
Okay I've just been reading over your code again in more detail. Forgive me, maybe I'm misreading it, but your code is formalising permutations as injective functions of the form `Fin n → Fin n`? Surely this is a subset relation and not a permutation relation? A permutation would be bijective...

I'd imagine formalising the notion of a permutation as follows:
```agda
IsPermutation : ∀ {n} → (Fin n → Fin n) → Set
IsPermutation f = Bijection (setoid (Fin n)) (setoid (Fin n)) f
```

**Comment by zhyltsovd** [comment]
@MatthewDaggitt No, it's not the case. The point was to formalize so-called [Lehmer code](https://en.wikipedia.org/wiki/Lehmer_code) via inductive family. First I did so for the type of permutations and then I was able to generalize it for finite injective functions. Thus the following type `Inj` represents injective functions from `Fin n` to `Fin m` structurally:
`data Inj : Nat → Nat → Set where`
`[]  : {m   : Nat} → Inj 0 m`
 `_∷_ : {n m : Nat}(x : Fin (ns m))(p : Inj n m) → Inj (ns n) (ns m)`

And for any `n` type `Inj n n` represents the type of permutations. In my view it's more convenient way to represent permutations because it gives associated induction principle!

**Comment by MatthewDaggitt** [comment]
> No, it's not the case. Let S be a finite set, and f: S -> S a function. Then the following are equivalent: f is injective; f is surjective; f is bijective.

Ah yes, my fault, not quite sure why I'd forgotten we were finite! Thank you for your explanation. I have to confess when I read it the first time I completely misunderstood what your code was trying to do. 

Now that I'm more on-board, I'm afraid I don't think that the code is generally applicable enough for the standard library. Nothing to do with the code quality or its usefulness in certain situations! It's just that we try and keep the number of data types in the standard library to a minimum, and `Inj` is really just a special case of `Fin n → Fin m`, albeit one where the induction principle is easy to access.

Once again, apologies for the numerous misunderstandings on my part. However if you have functions along the lines of `thin` and `thick` (which were missing until recently) that you think are both widely applicable and missing from the standard library please do feel free to contribute them. I promise you'll get a quicker response!

**Comment by zhyltsovd** [comment]
@MatthewDaggitt That's ok, no inconvenience caused! I think we can just close this pull request.

**Pull request closed without merging**
