### PR TITLE
point at Induction.Nat in docs of Data.Nat.Base

### PR DESCRIPTION
**Pull request by strake**
I figured there must be an eliminator defined in the standard library, but it took me a while to find it...

### CODE REVIEW

**Comment by MatthewDaggitt** [comment]
Yup, there's been some discussion about whether this is misplaced or not.

**Comment by gallais** [comment]
It would make sense to `import Induction.Nat` so that users can easily navigate
to it in the file / rendered documentation. (It also forces us to remember to update
the comment if we do end up moving the file / its content).

**Comment by strake** [comment]
@gallais PTAL, is it what you mean?

**Comment by gallais** [comment]
Oh sorry, I thought you were talking about `README.Nat`, not literally `Data.Nat.Base`.

**Comment by gallais** [comment]
If you're looking for an eliminator, `GeneralisedArithmetic` is also a
good place to have a look at btw

https://agda.github.io/agda-stdlib/Data.Nat.GeneralisedArithmetic.html

**Comment by MatthewDaggitt** [comment]
Superseded by #741

**Pull request closed without merging**
