### PR TITLE
`Data.List.Base.reverse` is self adjoint wrt `Data.List.Relation.Binary.Subset.Setoid._⊆_`

### PR DESCRIPTION
**Pull request by jamesmckinna**
This is a partial fix to #2353 but organised slightly differently, for consistency with existing uses of `reverse⁺` and `reverse⁻`, via a self-adjointness property of independent interest itself generalising the corresponding self-inverse property for `List.reverse`. 

Not done: extension to `Data.List.Relation.Binary.Sublist.Setoid._⊆_` (nor its `Heterogeneous` generalisation), which seems a *lot* more fiddly to achieve.

### CODE REVIEW

**Review by JacquesCarette — APPROVED** [review]

**Comment by jamesmckinna** [comment]
Possible additions? I didn't think to add these earlier, but they are in scope for this PR:
```agda
  reverse-η : ∀ {xs} → xs ⊆ reverse xs
  reverse-η = Membershipₚ.reverse⁺ S

  reverse-ε : ∀ {xs} → reverse xs ⊆ xs
  reverse-ε = Membershipₚ.reverse⁻ S
```
with the `-η`/`-ε` designations referring to the unit and counit of the self-adjunction...

**Comment by JacquesCarette** [comment]
It almost feels like adding too many synonyms goes overboard? Doesn't pass the Fairbairn test. I'd be tempted to add these *as comments* in the code.

**Comment by jamesmckinna** [comment]
> It almost feels like adding too many synonyms goes overboard? Doesn't pass the Fairbairn test. I'd be tempted to add these _as comments_ in the code.

Fair enough! The alternative would be to take those synonyms out of `Membershipₚ` (where they've been added as part of this PR from `Any`)  in favour of direct implementation here... but on balance your suggestion re:comment seems a good one.

**Review by Taneb — APPROVED** [review]
Is this also true for `Data.List.Relation.Binary.Sublist`? In which case we should add it there also, but that can be a separate PR

**Comment by jamesmckinna** [comment]
> Is this also true for `Data.List.Relation.Binary.Sublist`? In which case we should add it there also, but that can be a separate PR

So that *is* a good question:
* yes, I think so
* but I found it 'not easy' to prove directly
* and so left it above as a downstream TODO...

That said, maybe it's *not* true? Either way, any attempt to prove it by going via a property of `reverseAcc` seems to get tangled up between any instances of sublist relations of the two arguments to that function...

**Review by andreasabel — APPROVED** [review]

**Pull request merged**
