### PR TITLE
Synchronization PR

### PR DESCRIPTION
**Pull request by JacquesCarette**
There is actually no change at all in this PR, but git believes that I've got 8 commits ahead of upstream, and I think this is the easiest way to synchronize things.  Of course, I'd be happy to learn of a better way!

### CODE REVIEW

**Comment by MatthewDaggitt** [comment]
Err so you want me to merge this in? Might be easier to download a fresh copy of the repository?

**Comment by erydo** [comment]
It looks like you may have meant either to perform a rebase, or to merge agda/agda-stdlib@master into your local branch.

**Comment by JacquesCarette** [comment]
@MatthewDaggitt If all it needed was to download a fresh copy, I would have done that. But I have a 'fork' on github that tracks upstream. I don't want to nuke it and re-fork, that seems wrong.

@erydo I did merge agda/agda-stdlib@master into my local branch. That's how I got into this mess. Maybe I do want to do some kind of rebase. Specific advice welcome, I would be quite happy to ditch this PR for something less silly!

**Comment by MatthewDaggitt** [comment]
Sorry, yup, that was me stating the obvious, apologies! :worried: I have to confess I'm a bit reluctant to merge this in to fix someone's local problems. I'm afraid I don't have any specific git advice...

**Comment by erydo** [comment]
@JacquesCarette, are there any changes in that branch you meant to keep? I assume not because it's a no-op commit. If you're trying to set your the `master` branch on JacquesCarette/std-lib to the same as here, you can do something like:
```
# What are your remotes called?
git remote -v
```

Should be something like:
```
JacquesCarette  git://github.com/JacquesCarette/agda-stdlib.git (fetch)
JacquesCarette  git://github.com/JacquesCarette/agda-stdlib.git (push)
origin  https://github.com/agda/agda-stdlib (fetch)
origin  https://github.com/agda/agda-stdlib (push)
```

If so, using the correct names below (maybe instead of `origin` it's called `agda` or `upstream`, it depends on how it was set up):
```
# Downloads all of the commits locally
# (Doesn't change the state of anything)
git fetch --all

# Stash your local changes, just in case.
# This basically makes a temporary commit.
git stash

# Get onto the master branch. Note that "master" here refers to your _local_ repo.
git checkout master

# Set your local master branch to the same commit as the stdlib's master branch
# Keep in mind it might not be "origin" below.
git reset --hard origin/master

# Fix the master branch on your fork by forcing it to point to the commit you're on.
git push --force-with-lease JacquesCarette master

# Restore any local edits you might have been in the middle of
git stash pop
```

**Comment by JacquesCarette** [comment]
I completely agree that merging this to fix my local problems seems a bit much - but now I know how to get myself out of this bind thanks to @erydo .

**Comment by JacquesCarette** [comment]
Just to confirm that that worked. Thanks again.

**Pull request closed without merging**
