### PR TITLE
primFloatToWord64 now returns a Maybe

### PR DESCRIPTION
**Pull request by UlfNorell**
Required changes for agda/agda#6156. The issue is agda/agda#6093.

**THIS SHOULD NOT BE MERGED INTO `master`**, but it seems `experimental` is not up to date?

### CODE REVIEW

**Comment by MatthewDaggitt** [comment]
Yes, `experimental` hasn't been kept up to date because this is the first breaking change to Agda since our last release. I've just updated it so if you could reopen this PR against it instead of `master` that would be great!

**Comment by gallais** [comment]
No need to reopen we can manually redirect the target.

**Comment by MatthewDaggitt** [comment]
Ooh thanks @gallais, didn't know about that feature!

**Comment by MatthewDaggitt** [comment]
Okay, once the upstream PR has been merged, will merge this in.

**Comment by UlfNorell** [comment]
Upstream is merged

**Comment by gallais** [comment]
CI updated :crossed_fingers:

**Pull request merged**
