### PR TITLE
Simplify `Data.Product` imports

### PR DESCRIPTION
**Pull request by Saransh-cpp**
Some straightforward simplifications of `Data.Product` to `Data.Product.Base`. 

This PR does not get rid of all the `Data.Product` imports. I'll be creating PRs for the same.

### CODE REVIEW

**Comment by gallais** [comment]
Some of these are already covered by #1995. We should maybe wait for that PR
to be merged to avoid duplicating too much work.

**Comment by Saransh-cpp** [comment]
The majority of the `Data.Product` imports were indeed only using `Data.Product.Base`.  I've simplified all of the `Data.Product` imports (excluding the ones importing `∃`, `∃-syntax`, ...) in my fork and will create PRs iteratively to avoid confusion.

The imports that I could not simplify involved importing `∃`, `∃-syntax`, ... from `Data.Product`. Moving `∃`, `∃-syntax`, ... to `Data.Product.Base` will simplify every `Data.Product` import in the library to `Data.Product.Base`, but I'm not sure if that should be done.

**Comment by Saransh-cpp** [comment]
Ah, #1995 already moves the problematic variables and operators to `Data.Product.Base`.

**Comment by MatthewDaggitt** [comment]
https://github.com/agda/agda-stdlib/pull/1995 is now merged, so this can be rebased.

**Review by gallais — APPROVED** [review]

**Pull request merged**
