### PR TITLE
Reorganisation of the new binary modules

### PR DESCRIPTION
**Pull request by MatthewDaggitt**
@mechvel your comment about planning to add binary representations of integers and rationals made me realise that the name `Bin` needs to change so that we can distinguish between naturals, integers and rationals.

This PR therefore:
 1) Renames the type `Bin` to `ℕᵇ`. I toyed with `ℕB` but I think the important thing is the `ℕ` not the `ᵇ`. This means we can add integers as `ℤᵇ` etc.
 2) Moves the files from `Data.Bin` to `Data.Nat.Binary`. Integers can then live in `Data.Integer.Binary` etc.
 3) Reintroduces the old implementation in `Data.Bin` for backwards compatibility. These old modules are marked as deprecated and will be removed in some future release.
 4) Renames the constants from `0B`, `1B` etc. to `0ᵇ`, `1ᵇ` to match the new name of the type.
 5) Removes the `B` from the names of any proofs that feature the above constants in their name.

@mechvel let me know what you think?

### CODE REVIEW

**Comment by mechvel** [comment]
> @mechvel let me know what you think?

My preliminary impression:  it is all right.

* I am going to PR ``Bin.Minus``, and while preparing it, I  will have an opportunity to "test" these  
  denotations more closely.
 * I believe, once in future it will come the representation of  ``ℕ`` with a list of macrodigits.
   Will it be called ``ℕᴹ`` ?
* In mathematics, ``ℕᵇ`` denotes  ``ℕ × ... × ℕ``  -- a direct product ``b`` copies of  ``ℕ``.
  But a direct product can be denoted in Agda programs as, say   ``×ᵇ ℕ``.
  ``ℕb`` sometimes denotes the set of numbers  multiple to ``b``, but in an Agda program it can be  
  denoted as ``ℕ*b``. 
  I think that  ``ℕᵇ`` and ``ℕb`` are equally good.
  Let the team choose this according to its taste.
  
Can you, please, swap pull/883 and _master_ with saving the copy of _master_
(call this copy _master0_) ?
So that _master_ will become with new names for Bin and also with today's merge you have done.
Then, I would clone this new _master_ and start a PR of Nat/Binary/Minus in order to merge it to this new _master_.
?

**Comment by MatthewDaggitt** [comment]
> Can you, please, swap pull/883 and master with saving the copy of master
(call this copy master0) ?
So that master will become with new names for Bin and also with today's merge you have done.
Then, I would clone this new master and start a PR of Nat/Binary/Minus in order to merge it to this new master.
?

I'm afraid I don't quite understand what you mean. If you would like to work with a version of the library with this pull request included and before it is merged into master, then you can run the following commands:
```
git fetch origin            -- fetches the latest version of this repository
git checkout nat-bin        -- checkouts the changes in this PR
git checkout -b bin-minus   -- starts a new branch with the above changes included
```

**Comment by MatthewDaggitt** [comment]
> I believe, once in future it will come the representation of ℕ with a list of macrodigits.
Will it be called ℕᴹ ?

As I understand your previous comments, macrodigits are simply numbers in a certain base. We already have a name for that in `Data.Digit`, namely `Expansion b` where b is some base. I'm open to renaming it, if and when we come to it.

**Comment by mechvel** [comment]
> If you would like to work with a version of the library with this pull request included and before it 
> is merged into master, then you can run the following commands:
>
> git fetch origin            -- fetches the latest version of this repository
> git checkout nat-bin        -- checkouts the changes in this PR
> git checkout -b bin-minus   -- starts a new branch with the above changes included

I would better wait till you merge this PR into master. 
(the last two second commands do not work in my situation).
Meanwhile I would prepare Bin.Minus under my local clone of  to-day's _master_ 
(September 10).

**Pull request merged**
