### PR TITLE
[ bug ] Fixed two bugs in `Rational`

### PR DESCRIPTION
**Pull request by MatthewDaggitt**
Found two bugs in `Data.Rational` that need to be fixed before v1.0

- the definition of addition was wrong (multiplying by the wrong denominator)
- the proof for division was not marked irrelevant

Also took the opportunity to add a little extra notation and clean the file up.

No backwards incompatibilities as this was all added this release.

### CODE REVIEW

**Comment by MatthewDaggitt** [comment]
Just come up with another simplification. The `norm-mkQ` operator was really just doing a better job of what the old `_÷_` operator was doing. So I've got rid of the old definition of `_÷_` and renamed `norm-mkQ` to `_÷_`. 

I then swapped the names for `_/_` and `_÷_` as the operator `_/_` is a **much** better match visually for a numerator over a denominator.

This last change is not backwards compatible, but the module was so empty before I don't think anyone can begrudge us. Pinging @Zambonifofex as I know they use this module.

**Comment by Zambonifofex** [comment]
Thank you for pinging me, @MatthewDaggitt! However, I can’t say I have actually used the module ever since I last mentioned it.

Perhaps not fully related to your changes in this pull request, though, I have kinda always felt like a rational type based around continued fractions would be much easier to use (for programming as well as proving), and I suspect it’d be more efficient too.

I always wanted to try to make an implementation, but I was never dedicated enough to sit down and do it. Do you reckon it’d be worth to open an issue as well as to try to implement it? Another advantage is that the same kind of mechanism could be used to create a `Codata.Real` module, which would allow people to represent almost all (if not all) useful real numbers.

**Comment by MatthewDaggitt** [comment]
> Do you reckon it’d be worth to open an issue as well as to try to implement it? Another advantage is that the same kind of mechanism could be used to create a Codata.Real module, which would allow people to represent almost all (if not all) useful real numbers.

I think there is this issue #590 for it already. I have to confess I don't quite understand the difference in the representation, how would a `Fraction` type be implemented?

But yes if you wanted to have a go at implementing it then go for it!

**Comment by Zambonifofex** [comment]
@MatthewDaggitt

I can’t say I fully understand the issue you linked, but I don’t think it is what I’m talking about at all.

The idea would be to represent rational numbers as a list of natural numbers representing their corresponding continued fraction.

The magic thing about continued fractions is that every continued fraction represents a unique rational number, i.e. (perhaps in a way that sounds more useful), every rational number has a single continued fraction representation, which means there would be no need to have a somewhat involved proof that its components are normalized.

I guess there is a catch, though. The above assertion is a lie, there are actually two representations for a single natural number, one that ends with `..., a, 1`, and another that ends with `..., a + 1`. However, the “normalization proof” should be much simpler than the current one.

Note also that I’m not particularly familiar with continued fractions. I remember reading about them a couple months ago (in particular, how to perform arithmetic operations on them efficiently), but I’d probably have to read s’more before attempting to implement them.

**Comment by MatthewDaggitt** [comment]
Hmm that's a neat idea. Hadn't come across that representation before! The fact that each rational has two representations is a bit of a blow (always complicates the implementation) but if you think it would be useful then by all means give it a go.

Having said that, I think this `Rational` module is slowly becoming more usable. I'm having fun proving various properties.

**Comment by jespercockx** [comment]
> I guess there is a catch, though. The above assertion is a lie, there are actually two representations for a single natural number, one that ends with ..., a, 1, and another that ends with ..., a + 1. However, the “normalization proof” should be much simpler than the current one.

Note that Agda has dependent types so there are ways to enforce properties like "the last number in this list should not be 1." :) Or you could just always interpret the last number as (1+) that number, which would even work in a simply typed language.

**Pull request merged**
