### PR TITLE
Refinement types plus `Null`/`NonNull`

### PR DESCRIPTION
**Pull request by jamesmckinna**
EXPERIMENTAL/DRAFT: See #2092.

`Refinement` types, and their syntax, are (at present) neither here nor there, but the rest of the PR is a moderately extended exploration of one mode of use: defining the `Refinement` associated with being `non-null` for a 'typeclass' supporting a `null`/`non-null` field... including `Nat`, `List`, ...

Possible target(s): 
- [x] safe `head` function on `List'; UPDATED superseded/specialised by #2260 ?
- [ ] reimplement `Data.List.NonEmpty`?
- [ ] what else?

### CODE REVIEW

**Comment by jamesmckinna** [comment]
Fixed merge conflict, but the (previously committed) line about `<-irrefl` now seems orphaned out-of-place. Something to pursue in tidying up `CHANGELOG` for v2.0...

**Comment by gallais** [comment]
Are you aware of http://agda.github.io/agda-stdlib/Data.Refinement.html ?

**Comment by jamesmckinna** [comment]
Oh, for heaven's sake, RTFL...! :facepalm: 
Thanks for the pointer. Sigh.

**Comment by jamesmckinna** [comment]
I'm going to close this, in favour of #2260

**Pull request closed without merging**
