### PR TITLE
New logical reasoning module

### PR DESCRIPTION
**Pull request by MatthewDaggitt**
This is a first attempt to create a reasoning module that mimics formal pen & paper proofs for arbitrary logic (as opposed to equalities/inequalities). It bears some resemblance to the pipelining found in `Function.Reasoning`.

Currently the my proposed default layout looks something like:
```
A⇒C : A → C
A⇒C a = begin⟨ a ⟩ ⇒ A
    ∴⟨ A⇒B ⟩ ⇒ B
    ∴⟨ B⇒C ⟩ ⇒ C ∎
```
but ideally I'd like the combinators to be laid out like the standard inequality and equality reasoning modules, i.e.
```
A⇒C : A → C
A⇒C a = begin⟨ a ⟩ 
  ⇒ A  ∴⟨ A⇒B ⟩ 
  ⇒ B  ∴⟨ B⇒C ⟩ 
  ⇒ C ∎
```
I'm not sure it's quite as semantically meaningful when read allowed though? Maybe someone has some bright ideas for renaming the `⇒` and `∴` symbols?

### CODE REVIEW

**Comment by alhassy** [comment]
Maybe take a look at @WolframKahl's [RATH-agda](http://relmics.mcmaster.ca/RATH-Agda/RATH-Agda-2.2.pdf), section 2.3.

**Comment by MatthewDaggitt** [comment]
> Maybe take a look at @WolframKahl's RATH-agda, section 2.3.

Wow, that's a serious piece of Agda. Interesting read, thanks for the heads up! I'm not sure if the combinator names in Section 2.3 quite capture what I'm after though.

Maybe if we just ditch the second symbol and have:
```agda
A⇒C : A → C
A⇒C a = begin⟨ a ⟩ 
  ∴ A  ⟨ A⇒B ⟩ 
  ∴ B  ⟨ B⇒C ⟩ 
  ∴ C  ∎
```

**Comment by gallais** [comment]
Is this [`Function.Reasoning`](https://agda.github.io/agda-stdlib/README.Function.Reasoning.html) with different names?

**Comment by MatthewDaggitt** [comment]
> Is this Function.Reasoning with different names?

Yes (modulo having a terminal operator, i.e. `id`). Sorry should have made that clearer. The problem is that the function pipeline terminology doesn't make for very readable proofs. This is an attempt at an alternative syntax that looks more like formal pen and paper proofs.

**Comment by MatthewDaggitt** [comment]
Still want to get this in, but going to wait until `v1.3` I think.

**Comment by JacquesCarette** [comment]
Is this really "logical reasoning"?  It is "just" very explicit forward composition that lets you see the intermediate types. It only has syntactic resemblance to logical reasoning.  Why not just `Function.Pipeline` or `Function.Chaining` or even `Function.Chaining.Explicit`?

In a way, this could be generalized (to `Semigroup`).

**Comment by MatthewDaggitt** [comment]
> Is this really "logical reasoning"?  It is "just" very explicit forward composition that lets you see the intermediate types. It only has syntactic resemblance to logical reasoning.  Why not just `Function.Pipeline` or `Function.Chaining` or even `Function.Chaining.Explicit`?

100% agree it is just forwards composition. I should probably be clearer what my aim is for this :+1: We already have almost identical code in `Function.Reasoning`, however (as highlighted in the [README](https://github.com/agda/agda-stdlib/blob/master/README/Function/Reasoning.agda)) this existing syntax is designed to emphasise the **functions** being composed. I'm after the same syntax but suitable for emphasising the **types** and would hopefully mimic the formal classical way of laying out proofs:
```
begin⟨ x-isOdd ⟩
⇒ IsOdd x             ⟨ lemma1 ⟩
⇒ IsOdd (3 * x)       ⟨ lemma2 ⟩
⇒ IsOdd (3 * x + 4)   ∎
```

For example this would make the proofs in `Data.Nat.Binary.Properties.toℕ-injective` much clearer. 

Out of interest how could it be generalised to `Semigroup`?

**Comment by JacquesCarette** [comment]
If you notice the core definition:
```agda
(⇒ A ∴⟨ f ⟩ g) x = g (f x)
```
you'll note that you could have written it as
```agda
(⇒ A ∴⟨ f ⟩ g) = g ∘ f
```
instead. And now the 'binary operation' is clearer.  But `Semigroup` was not quite right: you need a right identity too for ending chains.

**Pull request closed without merging**
