### PR TITLE
[ refactor ] moved the rest of modules into `Relation.Binary.Construct`

### PR DESCRIPTION
**Pull request by MatthewDaggitt**
In response to #438. 

Tidies up `Relation.Binary` folder by moving all the relevant submodules into `Relation.Binary.Construct`. Changed it to `Construct` instead of `Construction` as its a little shorter and pithier. Let me know if you prefer the old version.

Split up `Relation.Binary.Simple` and `Relation.Binary.InducedPreorders`. I don't really like the names for `Relation.Binary.Induced.ByPred/ByRel` though. @HuStmpHrrr do you have any suggestions?

### CODE REVIEW

**Comment by HuStmpHrrr** [comment]
I am not entirely sure. what about just `Relation.Binary.Induced.Predicate` and `Relation.Binary.Induced.Relation`? 

We probably just want to make sure naming is consistent across the library. as long as the literal meaning does not introduce ambiguity, i don't find it's too bad.

**Comment by MatthewDaggitt** [comment]
I considered those, but thought it might be misinterpreted as inducing a predicate, rather induced by a predicate... but maybe you're right and its clear from the context!

**Comment by HuStmpHrrr** [comment]
yeah, it reads like some predicate or relation is induced. do we have other module names that come with verbs in them?

**Comment by MatthewDaggitt** [comment]
> do we have other module names that come with verbs in them?

Not that I'm aware...

Hmm how about `Relation.Binary.Construct.FromPred/FromRel` instead of `Relation.Binary.Construct.Induced.ByPred/ByRel`? Still not keen on them though....

**Comment by HuStmpHrrr** [comment]
somehow I do feel `Relation.Binary.Construct.FromPred/FromRel` is slightly better. `Construct` kind of implies `Induced` already so that probably explains it. but I don't have a strong opinion. I think any of those would be fine as long as their names are consistent.

**Comment by MatthewDaggitt** [comment]
Okay, renamed as previously suggested.

**Comment by HuStmpHrrr** [comment]
wow, lots of refactoring! thank you very much for all these!

**Pull request merged**
