### PR TITLE
Add min/max/absolute value for ℚ

### PR DESCRIPTION
**Pull request by uzytkownik**
Various improvements to ℚ and ℤ

### CODE REVIEW

**Comment by MatthewDaggitt** [comment]
Thanks for the PR @uzytkownik, this is fantastic. However it is a huge amount to review in one go! Please could you split it into a few PRs. That should allow us to actually do a reasonable review on each of the parts and not have this PR stay open forever. The split I would suggest is as follows:

1. Lattice morphisms
2. Naturals and integers
3. Codata
3. Unnormalised rationals
4. Normalised rationals

The first three PRs can be submitted at the same time :+1:

**Comment by uzytkownik** [comment]
It looks like I made some mistakes during rebase so I need to fix them first. I will split the changes.

**Comment by MatthewDaggitt** [comment]
@uzytkownik given everything else has been merged in, I've rebased this branch to only contain the changes for rationals so that you still get the git credit for adding them. I'll go through and make the changes to the new style of min/max proofs.

**Comment by MatthewDaggitt** [comment]
Thanks for the PRs @uzytkownik, glad we managed to merge all of this one in!

**Pull request merged**
