### PR TITLE
Data.Container, second try

### PR DESCRIPTION
**Pull request by turion**
This is #123, hopefully fixed. All Data.Container.* compile. I still can't run GenerateEverything, but `runhaskell GenerateEverything.hs` finishes within a second without output or error. Is there another way to check that I haven't broken anything else?

### CODE REVIEW

**Comment by andreasabel** [comment]
You can put the generated `Everything.agda` into `src` and load it from there.  This will check the whole library.

**Comment by turion** [comment]
Awesome! (Why is it not already in `src` then?) The check succeeds.

**Comment by asr** [comment]
> finishes within a second without output or error

It was *too* fast.

Run `make clean` and try again.

**Comment by turion** [comment]
@asr, your recommended way of testing the library doesn't work for me. I referred to the method by @andreasabel, which took some two minutes and succeeded without error.

The error I'm having otherwise:
```
$ make clean && make test
find . -type f -name '*.agdai' -delete
cabal clean && cabal install
cleaning...
Warning: The package list for 'hackage.haskell.org' is 88 days old.
Run 'cabal update' to get the latest list of available packages.
Resolving dependencies...
Notice: installing into a sandbox located at
/home/turion/e/informatisch/Agda/agda-stdlib/.cabal-sandbox
Configuring lib-0.13...
Building lib-0.13...
Installed lib-0.13
GenerateEverything
make: GenerateEverything: Command not found
make: *** [GNUmakefile:12: Everything.agda] Error 127
```

**Comment by asr** [comment]
Thanks for the PR.

**Comment by andreasabel** [comment]
> Awesome! (Why is it not already in src then?) The check succeeds.

You have to ask the creator of the library.  
(It's like with the Creator: we can admire the wonders of creation, but we cannot understand all of His design decisions. :))

**Comment by andreasabel** [comment]
> The error I'm having otherwise:
> GenerateEverything
> make: GenerateEverything: Command not found
> make: *** [GNUmakefile:12: Everything.agda] Error 127

Can it be that the .cabal/bin directory (or whatever it is on your system) is not part of your PATH?

**Comment by turion** [comment]
Yes, that fixed it, thanks!

**Pull request merged**
