### PR TITLE
First step of float revision

### PR DESCRIPTION
**Pull request by wenkokke**
For when <https://github.com/agda/agda/pull/4885> is merged.

- Changed Data.Float.Base to import the new version of primitives.
- Changed Data.Float.Properties to remove the strict inequality induced via Word64.

### CODE REVIEW

**Comment by wenkokke** [comment]
@MatthewDaggitt: The changes to Float were merged upstream, so this should compile now with HEAD.

**Comment by gallais** [comment]
Let's see if it builds! :rocket:

**Comment by wenkokke** [comment]
It might not, due to the whole master is "broken" thing?

```sh
$ fix-whitespace --check
[ Violation detected ] src/Data/Sum/Algebra.agda
The command "fix-whitespace --check" exited with 1.
```

**Comment by gallais** [comment]
:scream: 

`experimental` looks good though

**Comment by MatthewDaggitt** [comment]
> It might not, due to the whole master is "broken" thing?

Apologies, my fault, it appears I had an old version of `fix-whitespace` installed which wasn't correctly detecting the violation. Fixed now.

**Comment by MatthewDaggitt** [comment]
@wenkokke once you've written a CHANGELOG entry explaining the changes, I'm happy to merge this in :+1:

**Comment by wenkokke** [comment]
@MatthewDaggitt updated the CHANGELOG

**Comment by MatthewDaggitt** [comment]
@wenkokke is there a reason you removed the `breaking` label? If I understand it correctly, this is a breaking change as it removes various things from `Data.Float` and `Data.Float.Properties`? Admittedly it's breaking because of upstream Agda changes, but it's still breaking right?

**Comment by MatthewDaggitt** [comment]
Will merge once Travis goes green.

**Comment by wenkokke** [comment]
@MatthewDaggitt misunderstood the semantics of the breaking label :)

**Comment by MatthewDaggitt** [comment]
Merging in as the tests seem to be passing, and it's only Stack that appears to be down.

**Pull request merged**
