### PR TITLE
[ fix #365 ] final step: comonad for Product

### LINKED ISSUE #365: Overhaul of `Data.X.Categorical`
So far we only have monad instances in:

* [x] Data.List.Categorical
* [x] Data.List.NonEmpty
* [x] Data.Maybe
* [x] Data.Sum.Categorical (coming up, #361)
* [x] Data.Product.Categorical (coming up, #378)
* [x] Add `RawMonadT` as an alias?

Bonus points: zippy applicatives for

* [x] Codata.Delay 
* [x] Codata.Stream
* [x] Codata.Colist
* [x] Codata.Covec
* [x] Data.Vec
* [x] Data.Product.N-ary
* [x] Add Identity Applicative (cf #396)
* [x] Cleanup [`lookup-morphism`](https://agda.github.io/agda-stdlib/Data.Vec.Categorical.html#2251) using Identity Applicative

Bonus bonus points: comonad instances for

* [x] Category.Comonad.Identity
* [x] Codata.Stream
* [x] Data.List.NonEmpty
* [x] Data.Product

Bonus^3 points:

To be able to define these notions as records, we would need to have level-polymorphic fields i.e. we would need a type for `Set omega`.

~~* [ ] introduce foldable~~
~~* [ ] introduce traversable~~
~~* [ ] refactor sequence(A/M), map(A/M), and for(A/M)~~

### PR DESCRIPTION
**Pull request by gallais**
I've called the two modules with results which do not require the
RawMonoid constraint `Base` but I'm open to suggestions for better
names.

### CODE REVIEW

**Comment by MatthewDaggitt** [comment]
> I've called the two modules with results which do not require the
RawMonoid constraint Base but I'm open to suggestions for better
names.

Do you need the `Base` modules at all? Could we not just make them anonymous instead?

**Comment by gallais** [comment]
Unfortunately we would have conflicting names `functor` and `comonad`.

**Comment by MatthewDaggitt** [comment]
Hmm thoughts on putting them both into their own modules i.e. `Data.Product/Sum.Categorical.Left/Right`? 

I always feel that nesting large named modules inside other modules is a bit like creating a matryoshka dolls... a pain to open!

**Comment by gallais** [comment]
I was thinking about that too and it may make things a bit cleaner.

But I think we would still need the `Product(ₗ/ᵣ)` submodules to be able to instantiate
the `RawMonoid` once and for all and get all the specialized definitions from `applicative`
to `forM`.

**Comment by MatthewDaggitt** [comment]
> But I think we would still need the `Product(ₗ/ᵣ)` submodules to be able to instantiate
the `RawMonoid` once and for all and get all the specialized definitions from `applicative`
to `forM`.

Yes you're right. I still think splitting them into two it would be an improvement though :smile: Should I merge this one in and we can do `Product` and `Sum` in a separate PR or should we do it in this one?

**Comment by gallais** [comment]
I had a look and although it works for `Sum`, I don't think it does for `Product`:
the `Base` module has some parameters which get instantiated when it is opened in
the main `Product` submodule.

So we can't make these parameters of the whole file (like we can in `Sum`). I guess
one solution would be to have `Data.Product.Categorical.(Left/Right).Base`?

**Comment by MatthewDaggitt** [comment]
> So we can't make these parameters of the whole file (like we can in Sum). I guess
one solution would be to have Data.Product.Categorical.(Left/Right).Base

Yes I agree, that sounds like the best solution. I've had a go at it and it does seem much easier to use in the examples file.

**Pull request merged**
