### PR TITLE
Add indexed functions in `Relation.Binary.HeterogeneousEquality`

### PR DESCRIPTION
**Pull request by DrPhil**
From issue https://github.com/agda/agda-stdlib/issues/274

### CODE REVIEW

**Comment by DrPhil** [comment]
The CHANGELOG types are not written. The other types were simplified somehow, but I couldn't understand the pattern well enough to simplify the new functions myself.
From the discussion it wasn't really clear if the combined icong and subst-removal was wanted. I added it so it's there if you decide you do want it.

**Comment by MatthewDaggitt** [comment]
Thanks! A couple of small tweaks now that I look at it more closely.

In the types could you move the `{i j : I}` to just before the declaration of `{x : A i} {y : A j}` as they're not needed for the `A` parameters.

> The CHANGELOG types are not written. The other types were simplified somehow, but I couldn't understand the pattern well enough to simplify the new functions myself.

There's no particular pattern, for most proofs we're just trying to give the key assumptions. I admit in this case it's particularly difficult. I think the best thing is just to put the everything from the `i ≡ j` proof downwards.

> From the discussion it wasn't really clear if the combined icong and subst-removal was wanted. I added it so it's there if you decide you do want it.

That's fine, although perhaps `≡-subst-removable-indexed` is possibly a better name, which is more inline with the other proofs at a quick glance.

**Comment by DrPhil** [comment]
I would be slightly confused by the name `≡-subst-removable-indexed`. The definition is only `hcong` and `≡-subst-removable` smashed together. I thought this might be convenient since it can be a quite common pattern and it is tedious to write out long types where Agda really could infer most of it:
```agda
open import Data.Vec
open import Data.Nat
open import Data.Nat.Properties
postulate
  A : Set
  l m n : ℕ
  xs : Vec A ((l + m) + n)
  f  : ∀ {n} → Vec A n → A

ys : Vec A (l + (m + n))
ys = P.subst (Vec A) (+-assoc l m n) xs

proof : f ys ≅ f xs
proof = icong (Vec A) (P.sym (+-assoc l m n)) f (≡-subst-removable _ _ _)
-- Written out fully:
-- icong (Vec A) (P.sym (+-assoc l m n)) f (≡-subst-removable (Vec A) (+-assoc l m n) xs)

proof₂ : f ys ≅ f xs
proof₂ = icong-≡-subst-removable _ _ f _
-- Even if Agda can not infer anything, it's still a lot shorter:
-- icong-≡-subst-removable (Vec A) (+-assoc l m n) f xs
```
I would have guessed that `≡-subst-removable-indexed` is the indexed version of `≡-subst-removable`, although I'm not even sure what that would be. If you still think that `≡-subst-removable-indexed` is a better name, just say so and I will change it!

If we include `icong-≡-subst-removable` I guess it would be logical to include `icong-subst-removable` as well, so I added it too. (Having the non-indexed versions (`cong-subst-removable` and `cong-≡-subst-removable`) are not as useful. There are no duplicated arguments there.)

**Comment by MatthewDaggitt** [comment]
> I would be slightly confused by the name ≡-subst-removable-indexed. The definition is only icong and ≡-subst-removable smashed together.

> I would have guessed that ≡-subst-removable-indexed is the indexed version of ≡-subst-removable, although I'm not even sure what that would be.

You're right, I was getting confused about what the lemma did.

> If we include icong-≡-subst-removable I guess it would be logical to include icong-subst-removable as well, so I added it too.

Good idea, thanks!

**Pull request merged**
