### PR TITLE
Fractional (1.5) fixity for `Relation.Nullary.¬_`

### LINKED ISSUE #1635: Precedence of negation and sigma/exists syntax
As pointed out by @jamesmckinna when trying to update PFLA to use v1.7 of the library (analysis below is his), currently you can't use `¬_` from `Relation.Nullary` and `∃[ A ] B` syntax (i.e. `∃-syntax`) from `Data.Product` without bracketing because the precedences are the wrong way around:

https://github.com/agda/agda-stdlib/blob/ed8efad584ccf0e96503371571bc0ed24ded62ee/src/Relation/Nullary.agda#L23

https://github.com/agda/agda-stdlib/blob/ed8efad584ccf0e96503371571bc0ed24ded62ee/src/Data/Product.agda#L78

So you can't write `¬ ∃[ A ] B`. The reason that it broke from v1.3 to v1.7 is that the fixity of the `∃-syntax` was first added by @Taneb in a0b06ba

So it looks like we need to switch the precedences somehow (`Σ-syntax` included). Anyone have any thoughts? We should probably have a look at what else has precedences in at the 2/3/4 level...

### PR DESCRIPTION
**Pull request by Saransh-cpp**
Fixes #1635 

This PR adds a fractional (1.5) fixity for `Relation.Nullary.¬_`, discussed as a possible solution to the issue in the thread.

Following the experiment of @jamesmckinna, I decided to put `¬` at level 1.5, and it did break `Data.Fin.Properties.¬∀⟶∃¬-smallest` (similar to setting it to 2) and `Data.List.Relation.Binary.Sublist.Setoid._⊂_` (I'm not sure why here, `_×_` and `¬_` have different fixities).

Adding brackets - `(¬ P i)` and `× (¬ (xs ≋ ys))` - worked and now `¬` is not at the same level as `Σ` and `_×_`. Using `¬ ∃[ A ] B` without any brackets works for me, but it would be nice if someone could check this on their end too. I'd also be happy to close this PR if everyone decides not to add the fractional fixity.

### CODE REVIEW

**Comment by MatthewDaggitt** [comment]
@Saransh-cpp thanks for the PR! As this is a breaking change, we definitely need a CHANGELOG entry. Otherwise it looks good.

**Comment by gallais** [comment]
What's the reasoning behind this? It does not seem to be shedding any parens
and actually forces us to introduce more. Is there really a need for this change?

**Comment by Saransh-cpp** [comment]
After this PR, the users won't need parens with `¬` and `∃-syntax` - `¬ ∃[ A ] B` would work fine (parens are required right now - `¬ (∃[ A ] B)` - should work the same for `Σ-syntax` as well).

But, changing the fixity of negation brings out some conflicts with `×`'s fixity. Its like this PR fixes one parens problem, but adds another minor parens problem, and I am not sure how to deal with that. I'll be happy to make edits to the CHANGELOG or close this.

**Comment by MatthewDaggitt** [comment]
Thanks for raising it @gallais! Yup, given the discussion in #1635 I think the solution proposed there of adding special syntax for negated existentials is a better way of fixing of the problem. 

Therefore I'm closing this PR. Thanks for exploring it @Saransh-cpp !

**Pull request closed without merging**
