### PR TITLE
[ refactor ] more general version of _--_ et al.

### PR DESCRIPTION
**Pull request by gallais**

### CODE REVIEW

**Comment by MatthewDaggitt** [comment]
Could we make this backwards compatible by having them be exported from `Data.List.Any`? I guess similar to #553. Also this isn't passing the tests.

**Comment by ice1000** [comment]
This should probably be squashed to prevent the 8000+ lines change 6d2e69a8c29fffdde460a49314bb4b42a2116dfb

**Comment by gallais** [comment]
We pretty much always squash PRs before merging them (which is super easy to do
thanks to github's web interface).

**Comment by gallais** [comment]
As I mentioned on the code:

The re-export in `Data.List.Membership.Setoid` screws us: `_∷=_` and `_─_` now have additional parameters that cannot be inferred.

The type of `_─_` from inside `Data.List.Relation.Unary.Any`:
```
{P.a : Level} {A : Set P.a} {P.p : Level} {P : Pred A P.p}
(xs : List A) →
Any P xs → List A
```
and from inside `Data.List.Relation.Unary.Any.Properties`:
```
{a : Level} {A : Set a} {P.a : Level} {A = A₁ : Set P.a}
{P.p : Level} {P : Pred A₁ P.p} (xs : List A₁) →
Any P xs → List A₁
```
(where it has been re-exported via the Membership hierarchy).

**Pull request merged**
