### PR TITLE
Pr#1709 bis

### PR DESCRIPTION
**Pull request by jamesmckinna**
These are some loose ends from `#1709`. No changes to record in `CHANGELOG`.

### CODE REVIEW

**Comment by MatthewDaggitt** [comment]
@jamesmckinna unfortunately you seem to have branched off of the [pr1709-bis](https://github.com/agda/agda-stdlib/pull/1734/commits/e44298f40b422b03ebae6f99611d4653efa37aba) branch rather than the `master` branch of your repo when you created this PR. Therefore you've got an extra commit at the start.

Two options. When that PR gets merged, then we can merge this again and hopefully it'll come out in the wash. Or you can remove the offending extra commit at the beginning by doing a rebase. Up to you.

**Comment by jamesmckinna** [comment]
Aaaargh! Sorry. Tired/careless/sloppy brain. 
Re: the two options. I'd go for the first, as I'm not quite ready to master rebase'ing a git repo.

**Comment by gallais** [comment]
The rebase here would be confined to a single branch. You have 11 commits on this branch so

```shell
git rebase -i HEAD~11
```
should give you a list of all of them in your editor of choice. You can then drop the first one (by
simply removing the line) and *voilà*.

**Comment by jamesmckinna** [comment]
And then another  `push` from my local rebased repo to GitHub? That seemed to fail...

**Comment by gallais** [comment]
Yeah you do need to push force

**Pull request merged**
