### PR TITLE
Parametrize module morphisms by raw bundles

### PR DESCRIPTION
**Pull request by Taneb**
Follow-on from #2263. These changes are breaking, although I think they're still important and worth it.

### CODE REVIEW

**Comment by jamesmckinna** [comment]
Obligations to discuss this, but I think the fact that this turn to indexing on `RawX` is already established (though the underdevelopedness of many homomorphisms under `Algebra.*` suggests that we have yet to really stress-test our designs?) suggests that this is a worthwhile breaking change.

Might (eventually) be worth polling as to how much the existing `Algebra.Module.*` hierarchy is already used in anger... or not.

**Comment by Taneb** [comment]
The very scientific method of typing `language:Agda "Algebra.Module.Morphism"` into the GitHub search bar only came up with various forks of stdlib, so it doesn't look like there's many consumers of this.

**Review by JacquesCarette — APPROVED** [review]
This is clearly trickier, but is also code that should succumb to 'smart' automation.

**Comment by Taneb** [comment]
Ugh, `Algebra.Module.Morphism.ModuleHomomorphism` broke. @jamesmckinna went over that module with me at the AIM in Delft lass year and I remember us working out that everything in there was either trivial or impossible to use

**Comment by jamesmckinna** [comment]
> Ugh, `Algebra.Module.Morphism.ModuleHomomorphism` broke. @jamesmckinna went over that module with me at the AIM in Delft lass year and I remember us working out that everything in there was either trivial or impossible to use

Yes! And what we did not do then (alas!) was raise an issue about it there-and-then, if only to be able to return to it now...
Propose that you do not that now, and we tackle it as a separate PR, uncoupled from this one... (to the extent that that is possible; are they completely orthogonal, or would this need to be merged first beforeproceeding?)

**Comment by Taneb** [comment]
It can be a separate PR in either order with no problem.

**Comment by MatthewDaggitt** [comment]
> The very scientific method of typing language:Agda "Algebra.Module.Morphism" into the GitHub search bar only came up with various forks of stdlib, so it doesn't look like there's many consumers of this.

This is a peripheral and new enough module, that I think it's acceptable to make a breaking change.

**Comment by Taneb** [comment]
Can this be merged?

**Pull request merged**
