### PR TITLE
remove unnecessary condition in the `Relation.Binary.Reasoning.Base.Apartness`

### PR DESCRIPTION
**Pull request by damhiya**
`Transitive _#_` condition in the module `Relation.Binary.Reasoning.Base.Apartness` is unnecessary. Indeed, apartness relation can be transitive only if it is empty, and I think the module name is not appropriate since this module just works for any symmetric relation.

### CODE REVIEW

**Review by JacquesCarette — CHANGES_REQUESTED** [review]
Agreed - but needs a CHANGELOG entry!

**Comment by damhiya** [comment]
Is there any opinion about changing the module name?

**Comment by MatthewDaggitt** [comment]
Sorry for the long reply time. 

> Is there any opinion about changing the module name?

As always, it's easy to say the current name isn't the best. Do you have a better suggestion we can compare it with? I personally don't think the current name is terrible.

@JacquesCarette would you be willing to approve now?

**Review by MatthewDaggitt — APPROVED** [review]

**Comment by damhiya** [comment]
I recommend `Relation.Binary.Reasoning.Base.Symmetric`.

**Review by JacquesCarette — APPROVED** [review]
I'm fine with this PR doing just the removal of the condition. Name changes can be in a different PR.

**Comment by JacquesCarette** [comment]
Looking in more detail: what's in the file seems quite consistent with its current name - it is base reasoning about an apartness relation!

**Comment by MatthewDaggitt** [comment]
I'm also tempted to agree with @JacquesCarette. It's also not as if it's a very widely used module outside of the library.

**Pull request merged**
