### PR TITLE
[ #715 ] Fixed the bug in `Reasoning.MultiSetoid` reasoning by reimplementing it.

### LINKED ISSUE #715: Unsolved metas when using Relation.Binary.Reasoning.MultiSetoid
Agda version: 2.6.0
Stdlib version: 1.0
Test case:
```
open import Level using (zero)
open import Relation.Binary using (Setoid)
open import Relation.Binary.Reasoning.MultiSetoid using (begin⟨_⟩_ ; _≈⟨_⟩_ ; _∎)
open import Relation.Binary.Reasoning.Setoid using (_IsRelatedTo_ ; relTo)

module Bug (S : Setoid zero zero) where

  open Setoid S

  bug₁ : ∀ x → x ≈ x
  bug₁ x = begin⟨ S ⟩ x ≈⟨ refl ⟩ x ∎

  bug₂ : ∀ x → x ≈ x
  bug₂ x = begin⟨ S ⟩ (relTo refl)
```

Agda reports unsolved metas of type `Relation.Binary.Symmetric _≈_` in `bug₁` and `bug₂`. Perhaps this is because `Reasoning.MultiSetoid` is ultimately defined in terms of `Reasoning.Base.Single`, whose `_IsRelatedTo_` does not mention symmetry.

### PR DESCRIPTION
**Pull request by MatthewDaggitt**
Fixes #715 by re-implementing `Reasoning.MultiSetoid` on it's own terms rather than going through `Reasoning.Setoid`. 

I think this fixes the problems, at least I can't seem to break it. @JLimperg could you give it a whirl and let me know?

### CODE REVIEW

**Comment by JLimperg** [comment]
I can confirm that the reimplementation works for my use case. Thanks for the quick fix!

As a bonus, perhaps you could add the combined transitivity/symmetry combinator, for parity with `Reasoning.Setoid`:

```
  infixr 2 _≈˘⟨_⟩_

  _≈˘⟨_⟩_ : ∀ x {y z} → y ≈ x → IsRelatedTo S y z → IsRelatedTo S x z
  x ≈˘⟨ x≈y ⟩ y∼z = x ≈⟨ sym x≈y ⟩ y∼z
```

**Comment by JacquesCarette** [comment]
Yes please on that combinator!

**Comment by MatthewDaggitt** [comment]
Yup, didn't realised I'd missed that one. Once travis goes green, I'll merge it in and put together a release for v1.0.1.

**Comment by JLimperg** [comment]
Excellent, thank you so much!

**Pull request merged**
