### PR TITLE
Added the Selectivity property to FunctionProperties

### PR DESCRIPTION
**Pull request by MatthewDaggitt**
Added the Selectivity property for operators. Useful when working with "choice" operators such as "min" or "max".

Obviously being selective implies the operator is idempotent as well. As this is my first contribution I'm a bit hesitant about adding this proof to FunctionProperties.agda as there are no other "properties of properties" proofs so to speak. However looking around I don't think there's any other suitable places... I'm happy to listen to advice!

### CODE REVIEW

**Comment by andreasabel** [comment]
Please also supply a use case that argues this property is common and useful enough to be included in the standard library.

**Comment by MatthewDaggitt** [comment]
As in add a use case in the library itself? Or describe a theoretical use case?

For a theoretical one, a useful generalised proof is to that if some property holds of both arguments, then it will hold over the result of an application of a selective operator. Also sets are always closed under selective operators.

A more concrete example, they represent the class of "choice" operators (the simplest of which are min, max, left, right etc.). For example in my work they appear twice. My first use-case is to provide witnesses to the outcomes of the min and max operators in Data.Nat. The second time is when I'm formalising routing algorithms algebraically and a selective operator allows me to model abstractly choosing between routes. 

Finally, as mentioned above, it's related to idempotence which has made it into the library.

**Comment by andreasabel** [comment]
So, you could bundle with this patch proofs of Selective for min and max in Data.Nat.Properties.  This would provide an example use for Selective.

**Comment by MatthewDaggitt** [comment]
Okay, done. Thanks!

**Comment by andreasabel** [comment]
You put the properties in the section: "Various order-related properties".  Maybe it is better to open a new section "Selectiveness of min and max" and put it under the distributive lattice stuff for min and max.

**Comment by MatthewDaggitt** [comment]
You're right, I'm not sure why I put it there. A moment of madness! Thanks for your patience.

**Comment by andreasabel** [comment]
I squashed your 4 commits into 1. So you might have to do a fresh clone of the standard library.
Thanks for the contribution!

**Pull request merged**
