### PR TITLE
[ new ] synonym for Level.zero

### PR DESCRIPTION
**Pull request by MatthewDaggitt**
An extension to the `ℓ` naming convention for levels that's used throughout the library. In a lot of places we write `Level.zero` or `zero`. The former is verbose and requires `as Level` in the header and the latter is sometimes confusing when dealing with numeric datatypes.

Thoughts? Is `ℓ` used for anything else that I'm forgetting?

### CODE REVIEW

**Comment by gallais** [comment]
> The former is verbose and requires `as Level` in the header

I don't think we need `as Level` as the module is already called `Level`. ;)

**Comment by JacquesCarette** [comment]
I am seriously unsure about the synonym `ℓ₀ = zero`. `ℓ₀` looks like a variable (obviously). And I certainly have seen code that uses a bunch of levels use `ℓ` with subscripts (i.e. when you have 5+ levels).

When reading code quickly, I am pretty sure that I would read code that uses `ℓ₀` as being Level polymorphic.

`0ℓ` on the other hand would read primarily as `0` qualified to be a Level. Which is the most important point I am making here: whatever synonym you use, should read primarily as `0` rather than primarily as a variable.

**Comment by gallais** [comment]
`ℓ₀` does look like a popular variable name for levels: https://github.com/search?l=Agda&q=%E2%84%93%E2%82%80&type=Code

**Comment by MatthewDaggitt** [comment]
@JacquesCarette excellent point. I'll change it to `0ℓ`.

**Comment by MatthewDaggitt** [comment]
Updated.

**Comment by gallais** [comment]
Lovely!

**Pull request merged**
