### PR TITLE
Release v1.7.2

### PR DESCRIPTION
**Pull request by MatthewDaggitt**
**Should not be merged.**

This is a branch off of `v1.7.1` tag. I'm opening a PR for CI purposes only.

### CODE REVIEW

**Comment by gallais** [comment]
Should we also add
```
flags:
  --warning=noUnsupportedIndexedMatch
```
to the `.agda-lib` file?

**Comment by MatthewDaggitt** [comment]
> Should we also add
> 
> flags:
>   --warning=noUnsupportedIndexedMatch
> to the .agda-lib file?

Err haven't been following that discussion closely on the Agda repo. What are the pros and cons of it?

**Comment by gallais** [comment]
cf. #1866

**Comment by MatthewDaggitt** [comment]
Ah yes, we should. Thanks for the heads up!

**Pull request closed without merging**
