### PR TITLE
[ new ] combinators for List's All

### PR DESCRIPTION
**Pull request by gallais**

### CODE REVIEW

**Comment by MatthewDaggitt** [comment]
Sorry, this somehow slipped under my radar. I've actually been using a generalisation of `toList` and `fromList`:
```agda
reduce : ∀ {a b} {A : Set a} {B : Set b} {P : Pred A p} →
             (f : ∀ {x} → P x → B) → ∀ {xs} → All P xs → List B

construct : ∀ {a b} {A : Set a} {B : Set b} {P : Pred A p} →
                  (f : B → ∃ P) (xs : List B) → All P (map (proj₁ ∘ f) xs)
```
For example `reduce fromℕ≤ : ∀ {xs} → All (_< n) xs → List (Fin n)`

I think `toList = reduce _,_` and `fromList = construct id`. Maybe we should consider adding these instead?

**Comment by gallais** [comment]
`construct` feels a bit like a `mapA` to me, but not really. It's strange.

One thing I like about `fromList` is that we don't lose the connection between
the input list and the output `All`. I guess I may more comfortable with a type
like this:

```agda
construct : (f : B → ∃ P) (xs : List B) → All P (List.map (proj₁ ∘ f) xs)
```

**Comment by MatthewDaggitt** [comment]
In the end I just added all of them. Much easier and clearer that way :smile: It turns out the full type of `construct` is much easier to use than the suggestion above, e.g. in the translation between `Fin` and `Nat` in `Data.Digit`, so I've added the original version.

**Comment by gallais** [comment]
Fair enough. :+1:

**Pull request merged**
