### PR TITLE
make `mkRawMonad` and `mkRawApplicative` universe-polymorphic

### PR DESCRIPTION
**Pull request by gshen42**
A simple change. I've run `make test` and everything type checks.

### CODE REVIEW

**Review by gallais — APPROVED** [review]

**Comment by JacquesCarette** [comment]
Unfortunately, `make test` missed something as the CI says:
```
/home/runner/work/agda-stdlib/agda-stdlib/src/Data/Product/Effectful/Examples.agda:14,1-62,37
Unsolved metas at the following locations:
  /home/runner/work/agda-stdlib/agda-stdlib/src/Data/Product/Effectful/Left.agda:52,10-19
when scope checking the declaration
  import Data.Product.Effectful.Left as .#Data.Product.Effectful.Left-16184305951820099816
```

**Comment by jamesmckinna** [comment]
@gallais is the expert on (these particular instances of) universe polymorphism, and I seem to recall that there was a problem with `(Raw)Applicative` ie it may not be a CI problem?

**Comment by JacquesCarette** [comment]
He is indeed the expert. As it turns out, I'd given a try at this a few years back and the problem then was that `Applicative` was defined in terms of the indexed version, and that would have needed some kind of level-to-level function. The better solution would have been to do a direct definition, but that was too backwards incompatible (at the time).

**Review by JacquesCarette — APPROVED** [review]
Looks good - let's hope the CI works this time.

**Pull request merged**
