### PR TITLE
Make life easier to Mac contributors

### PR DESCRIPTION
**Pull request by JacquesCarette**
- better error message upon encountering `'\r'` in files
- document setting of `autocrlf`

### CODE REVIEW

**Comment by MatthewDaggitt** [comment]
You appear to have some changes to `Data.Nat.InfinitelyOften` caught up in this... I think if you merge master they should disappear, but failing that can you re-make the PR?

**Comment by JacquesCarette** [comment]
Indeed - I'll try to fix that later today.

**Comment by bch29** [comment]
I think it would be better to make `GenerateEverything.hs` work with Mac OS line endings rather than add a warning. Also, the check doesn't seem to correctly detect the problem on my machine. I still get the error about too many file handles being open, rather than seeing the new error message.

**Comment by JacquesCarette** [comment]
I may have mis-described the issue: when you accidentally get Windows-style line endings on a Mac, things go awry. That is what my check is for.  (And I still have to fix the PR).  The 'too many file handles' problem is because of a different issue [but I forget the details of that one right now...]

**Comment by MatthewDaggitt** [comment]
> And I still have to fix the PR

So this isn't ready to merge just yet?

**Comment by JacquesCarette** [comment]
The change itself is, but the PR is messed up because I was still figuring my way around git. So there are some extra commits that should be removed. And I don't know how to do that - do you?

**Comment by MatthewDaggitt** [comment]
That's fine, I can squash all the commits into a single one when I merge. As long as the changes are right, then the intermediate steps won't matter.

**Pull request merged**
