### PR TITLE
Fix proof name with | in Data.Nat.Properties

### PR DESCRIPTION
**Pull request by Taneb**

### CODE REVIEW

**Comment by Taneb** [comment]
What's the convention with CHANGELOGing this kind of change?

**Comment by MatthewDaggitt** [comment]
I'd add a deprecation warning under the `Deprecated names` section. In this case as the change is visually indistinguishable you probably want to explicitly mention that it's the last character that has changed from `|` to `\|` in both the CHANGELOG entry and the deprecation message. That way we don't baffle users to much...

**Comment by MatthewDaggitt** [comment]
Thank you for cleaning up after me by the way :+1:

**Comment by Taneb** [comment]
I've added a note and updated the changelog. While doing so, I noticed that another identifier, recently added, had a similar issue, so I've also renamed that.

**Pull request merged**
