### PR TITLE
Functor and Monad instances for Sum

### PR DESCRIPTION
**Pull request by siddharthist**
I haven't done much programming with Agda's universes yet, so this might be total trash! I'm also not sure whether the functor instance is necessary with the monad instance... Anyway, I look forward to your reviews.

### CODE REVIEW

**Comment by andreasabel** [comment]
Thanks for the PR, @siddharthist !

The code looks fine, but...

Shouldn't there two instances, one for functoriality in the first type argument and one for the second?  I know that Haskell has only the one you provided, but this is because Haskell has no type-level lambda, so the other one does not exist there.  

Also, I am not sure we want to encourage the `Either`-as-error-monad style programming in Agda, since, frankly, from a software engineering perspective, it is a hack.

**Comment by siddharthist** [comment]
@andreasabel Sure, and I'm happy to write a second! I didn't even consider that, but it obviously makes sense 😄. 

With respect to your second point, perhaps you can elaborate? What should we expect people to use instead?

**Comment by andreasabel** [comment]
> With respect to your second point, perhaps you can elaborate? What should we expect people to use instead?

Well, something that has name or part of its name `Error` or `Except` or something, and whose constructors are also called appropriately, like `ok` and `fail` or something.

See also https://github.com/andreasabel/haskell-style-guide/blob/master/haskell-style.md : 
- records instead of tuples
- hand-rolled data types instead of Maybe, Either, ...

**Comment by siddharthist** [comment]
@andreasabel I see. While I agree that more descriptive type names are helpful from a readability/engineering standpoint, I think having isomorphic types with different names might be unhelpful from a verification standpoint (what if I want to use a lemma written about `Sum` for my `Error`-like type?). 

What do you think the optimal solution is? Should we define a `Sum`-like type with a better name and provide these instances for that?

**Comment by MatthewDaggitt** [comment]
Some feedback:

- Definitely not taking a side, but if `Sum` is being used then the first `helper` is simply `map id f` and the second `helper` is `[ id , g ]`
- Shouldn't this module be called `Data.Sum.Categorical` in line with the other new modules `Data.List.Categorical` and `Data.Vec.Categorical`?

**Comment by siddharthist** [comment]
@MatthewDaggitt Thanks, I wasn't aware of the `[ , ]` (though I definitely should've used `map`!). If the maintainers are interested in these instances, I'll make both the changes you suggest.

**Comment by MatthewDaggitt** [comment]
Hi @siddharthist, sorry for the long reply time! I'm happy to accept the contributions, if the following changes are made:
- Rename the module to `Data.Sum.Categorical`
- Use `[_,_]` and `map` as mentioned above.
- Remove the first comment in the file about Haskell convention for representing `error`s.
- Add a note in `CHANGELOG.md`

**Comment by siddharthist** [comment]
@MatthewDaggitt Where is the best heading under which to note these changes in the CHANGELOG?

**Comment by MatthewDaggitt** [comment]
> @MatthewDaggitt Where is the best heading under which to note these changes in the CHANGELOG?

Under `Backwards compatible changes`. Just mention that you've added the new module and briefly describe what you've added in it.

**Comment by gallais** [comment]
@siddharthist Where are we on this? I could have used these results yesterday! :D 
Do you need help with it? I can grab you `sum-instances` branch and nudge it over the
finish line if you want.

**Comment by siddharthist** [comment]
@gallais If you're ready to work on it, go for it! I can also try to get it done tonight.

**Comment by gallais** [comment]
The only thing missing is the updated CHANGELOG, isn't it?

**Comment by siddharthist** [comment]
I think so!

**Comment by gallais** [comment]
I guess github does not do cross-references between PRs? So for the record: I've opened #361

**Pull request closed without merging**
