### PR TITLE
[ fix #2086 ] new www deploy strategy

### LINKED ISSUE #2086: Generated Agda standard library HTML has no version information
@jwaldmann writes

> NB - I found it (mildly) confusing that there is no version information (in the url) at
https://agda.github.io/agda-stdlib/Data.Product.Relation.Binary.Lex.Strict.html

I wonder how we can add version information to the generated HTML? Ideally we don't really want the URL to change every time we make a release as that would make linking a nightmare....

### PR DESCRIPTION
**Pull request by gallais**
This is the end result: https://gallais.github.io/agda-stdlib/

### CODE REVIEW

**Comment by JacquesCarette** [comment]
While the landing page is rather hideous, the overall result is fantastic. [i.e. content great, a tiny bit of CSS to pretty things up would sure be nice.]

**Comment by gallais** [comment]
I've thrown in a bit of css & and Agda logo.
Additional contributions are welcome.

I've manually updated https://gallais.github.io/agda-stdlib/ to show the result.

**Comment by MatthewDaggitt** [comment]
Looks great to me. Is this ready to merge?

**Comment by gallais** [comment]
Yep!

**Pull request merged**
