### PR TITLE
Update decidable equality of reflected syntax

### PR DESCRIPTION
**Pull request by jespercockx**
This PR includes the required changes to the standard library that should be made together with https://github.com/agda/agda/pull/4722

### CODE REVIEW

**Comment by gallais** [comment]
I see this relies on a modified `Builtin` file so you will have to remember to
update the commit hash in `.travis.yml` for the experimental branch once the
upstream patch has landed.

**Comment by jespercockx** [comment]
Yes, I will update this once the upstream PR is merged (and before this PR is merged itself).

**Comment by jespercockx** [comment]
The corresponding PR in the main Agda repo has been merged, so this PR is now ready to be merged too.

**Comment by MatthewDaggitt** [comment]
Ooh I've just noticed the breaking tag after I've merged it in. @jespercockx any chance you could add a CHANGELOG entry with the details? (even if it's mostly just a pointer to the Agda changelog?)

**Pull request merged**
