### PR TITLE
Tree zippers

### PR DESCRIPTION
**Pull request by alexarice**
Adds leaf labelled trees, zippers and their properties

### CODE REVIEW

**Comment by gallais** [comment]
This looks good to me, however it gets me wondering whether it would not be
better to merge this with `Data.Tree.Binary` and have a structure with both
nodes & leaves (each having their own type).

**Comment by alexarice** [comment]
Then have an alias where either leaves or nodes are given the unit type?

**Comment by alexarice** [comment]
Should I go ahead and implement this?

**Comment by gallais** [comment]
I'd be in favour of it, yes!

**Comment by MatthewDaggitt** [comment]
Closed in favour of #1125

**Pull request closed without merging**
