### PR TITLE
Data.List.Unique - Lists Containing no Duplicates

### PR DESCRIPTION
**Pull request by jpm61704**
This is the first bit of work for encoding lists with no duplicate elements. This is based on the definition found in #467 made by @HuStmpHrrr which was never added to the standard library. The definitions in this file will hopefully be useful later in defining Kuratowski(Listable) finiteness of types for the standard library(see [Dependently Typed Programming with Finite Sets](http://firsov.ee/finset/finset.pdf)).

This is very much a work-on-progress and the PR is being made to get feedback throughout the module's development. This being said, suggestions are very welcome.

### CODE REVIEW

**Comment by MatthewDaggitt** [comment]
Thanks for the PR @jpm61704. This is definitely something that would be useful! Got a couple of thoughts.

Firstly we've recently created a new directory `Data.List.Relation.Unary` (see CHANGELOG for details)  which is where this should live (along with `All`, `Any` etc).

In fact that new folder is why I've been waiting to add my own implementation of this which I've had for a while:
- [AllPairs](https://github.com/MatthewDaggitt/agda-routing/blob/v1.0/RoutingLib/Data/List/Relation/Unary/AllPairs.agda)(.[Properties](https://github.com/MatthewDaggitt/agda-routing/blob/v1.0/RoutingLib/Data/List/Relation/Unary/AllPairs/Properties.agda))
- [Unique.Setoid](https://github.com/MatthewDaggitt/agda-routing/blob/v1.0/RoutingLib/Data/List/Relation/Unary/Uniqueness/Setoid.agda)([.Properties](https://github.com/MatthewDaggitt/agda-routing/blob/v1.0/RoutingLib/Data/List/Relation/Unary/Uniqueness/Setoid/Properties.agda))
- [Unique.Propositional](https://github.com/MatthewDaggitt/agda-routing/blob/v1.0/RoutingLib/Data/List/Relation/Unary/Uniqueness/Propositional.agda)([.Properties](https://github.com/MatthewDaggitt/agda-routing/blob/v1.0/RoutingLib/Data/List/Relation/Unary/Uniqueness/Propositional/Properties.agda))

The generalised formulation is a tiny bit different:
```
data AllPairs {a ℓ} {A : Set a} (_~_ : Rel A ℓ) : List A → Set (a ⊔ ℓ) where
  []  : AllPairs _~_ []
  _∷_ : ∀ {x xs} → All (x ~_) xs → AllPairs _~_ xs → AllPairs _~_ (x ∷ xs)
```
but the generalised version is much nicer to work with as it doesn't have any negative terms in it which can make the proofs a bit more fiddly and verbose. The generalised form also works for `Sorting` which is another nice feature.

I'm not sure how much work you've done with your definition, but I'm happy to put up a PR with the contents of mine in the next few days if it would save you some time? I was planning to anyway before the release of v1.1.

**Comment by HuStmpHrrr** [comment]
I agree that a specific definition is probably too restrictive; `AllPairs` is better in many perspectives. It would be nice to have `Unique` to be a specialized `AllPairs`, and a good chunk of properties can just be carried over from ones of `AllPairs`'.

**Comment by jpm61704** [comment]
That sounds like a plan @MatthewDaggitt . As mention in the first comment I'm just getting this done so I can move on to Type Finiteness. If you already have it done that saves a ton of time. I'll use your definitions above until you make that PR.

**Comment by MatthewDaggitt** [comment]
> That sounds like a plan @MatthewDaggitt . As mention in the first comment I'm just getting this done so I can move on to Type Finiteness. If you already have it done that saves a ton of time. I'll use your definitions above until you make that PR.

Okay great, I'll try and get it done tomorrow. Unfortunately it won't be merged in for v1.0 which is releasing in the next couple of days and already locked down, but it'll be in v1.1.

**Comment by MatthewDaggitt** [comment]
Superceded by #672

**Pull request closed without merging**
