### PR TITLE
Add `(Is)DecPreorder` to `Relation.Binary.*`

### LINKED ISSUE #2482: Missing structure/bundle in the `Relation.Binary.*` hierarchy?
We don't seem to define as `IsDecPreorder` an independent entity 'between' `IsPreorder` and `IsTotalPreorder`... and the associated bundle.

Should we?

### PR DESCRIPTION
**Pull request by jamesmckinna**
Fixes #2482 (I hope).

UPDATED: DONE knock-on consequences for #2481 ... which prompted these additions in the first place!

### CODE REVIEW

**Review by MatthewDaggitt — COMMENTED** [review]
Do we need to construct the `DecPreorder` objects in the other higher `Dec` bundles?

Otherwise, looks good!

**Comment by jamesmckinna** [comment]
> Do we need to construct the `DecPreorder` objects in the other higher `Dec` bundles?

Sigh... yes, we should. I haven't done one of these 'structural' PRs for a while... and they do give me a bit of a headache (eg wrt the `renaming` directives in the reexport of `isPreorder` in `IsPartialOrder` etc.). Maybe make this a downstream PR?

**Comment by MatthewDaggitt** [comment]
Sure

**Review by MatthewDaggitt — APPROVED** [review]

**Review by JacquesCarette — APPROVED** [review]

**Comment by jamesmckinna** [comment]
So I think the `Structures` story is OK, but the `Bundles` definitely need refactoring as regards their `module Eq` and `decSetoid` definitions are concerned. I'll take a look later tomorrow...

**Review by MatthewDaggitt — APPROVED** [review]
This all looks good! Nice job on the inheritance!

**Comment by MatthewDaggitt** [comment]
Merging in as @JacquesCarette has already approved.

**Pull request merged**
