### PR TITLE
Improved product relations

### PR DESCRIPTION
**Pull request by MatthewDaggitt**
Brings the `Data.Product.Relation` folder into line with new standards. In particular:
- Renamed `StrictLex` and `NonStrictLex` to `Lex.Strict` and `Lex.NonStrict` (no additional backwards compatible problems as they had already changed location in this release).
- Renamed `Pointwise` and `SigmaPointwise` to `Pointwise.NonDependent` and `Pointwise.Dependent`
- Deprecated the majority of names of proofs that use infix notation. Previously it was incredibly inconsistent when and where it was used (see the [NonStrictLex](https://github.com/agda/agda-stdlib/blob/master/src/Data/Product/Relation/NonStrictLex.agda) for an example of how bad it is currently). As the infix notation isn't usable anywhere outside of `Product` and `Sum` (e.g. in the equivalent files in `List`/`Vec`) I've just deprecated it all.

### CODE REVIEW

**Comment by laMudri** [comment]
I don't know whether it should go in a separate pull request or this one, but it seems to me that the relation defined in `Data.Product.Relation.Pointwise.Dependent` should be defined via `record` rather than `data`, just like `Σ`. I did this in 486d7486db6ea7033806d70e13eb553e3f55bb86. As far as I understand, this shouldn't break anything (except if some other code contains value declarations for `proj₁` and `proj₂` and doesn't already import those names from `Data.Product`), but I haven't tried recompiling the whole stdlib.

**Comment by MatthewDaggitt** [comment]
> I don't know whether it should go in a separate pull request or this one, but it seems to me that the relation defined in Data.Product.Relation.Pointwise.Dependent should be defined via record rather than data, just like Σ. 

That seems reasonable from a semantics perspective. Do you have any other more concrete advantages in mind?

**Comment by laMudri** [comment]
Personally, I wanted to either have projection functions or do pattern matching in a `let`. If I remember my example correctly, I have proof-irrelevant subsets formalised as setoids where the carrier is `Σ A P` and the equivalence relation is the original equivalence relation on `A` paired with `Always`. Then I need a `proj₁` to use the equivalence relation on `A`. Using a pattern matching `λ` is just a bit more clumsy, and I didn't see any projection functions in stdlib.

**Comment by MatthewDaggitt** [comment]
Okay, I've implemented the changes and they seem to go through without any problems. Thanks for the suggestion.

**Pull request merged**
