### PR TITLE
Reworking `Data.Vec.Relation.Equality`

### PR DESCRIPTION
**Pull request by MatthewDaggitt**
In line with trying to get all major changes to Data.X.Relation modules out of the way before releasing 0.15:
- Split `Data.Vec.Relation.Equality` into:
   - `Data.Vec.Relation.Equality.Setoid`
   - `Data.Vec.Relation.Equality.DecSetoid`
   - `Data.Vec.Relation.Equality.Propositional`
   - `Data.Vec.Relation.Equality.DecPropositional`
- Renamed modules `Data.Vec.Relation.InductivePointwise/ExtensionalPointwise` to `Data.Vec.Relation.Pointwise.Inductive/Extensional`. No backwards compatibility issues as these are new modules since 0.14
- `Data.Vec.Relation.Pointwise.Inductive` is now semi-heterogeneous in that the two vectors can technically have two different lengths (although in practice they cannot). Should cause only very minor (if any) problems for people writing their own pointwise proofs, but allows a far wider range of proofs to be proved (e.g. `[]` is an right identity for `++`).
- All equalities now implemented via `Data.Vec.Relation.Pointwise.Inductive`
- @sstucki I'm so sorry, I've changed the name of your `gmap` again :stuck_out_tongue: . It's now called `map⁺`. If you look in `Relation.Pointwise.Inductive` it should be obvious why.
- Got rid of that horrible module `UsingVecEquality` in `Data.Vec.Properties`

I will change the structure of `List.Relation.Equality/DecidableEquality` to match.

Any comments?

### CODE REVIEW

**Comment by sstucki** [comment]
> It's now called `map⁺`

Sure, no problem. Just for the record, I adopted the name `gmap` from the [Vec.All.Properties](https://github.com/agda/agda-stdlib/blob/master/src/Data/Vec/All/Properties.agda#L44) module, not sure why it isn't called `map⁺` there...

**Comment by sstucki** [comment]
@MatthewDaggitt, I just realized that the new `Pointwise` datatype from Data.Vec.Relation.Pointwise.Inductive does not typecheck when the `--without-K` option is enabled, while the old `Pointwise′` from Relation.Binary.Vec.Pointwise did. Some universe levels seem to have been dropped. Is there any reason for that?

I don't know if there's any policy w.r.t. the use of axiom K, but I think it might be good to have as little of the standard library rely on it as possible. WDYT?

BTW, the reason I checked with `--without-K` in the first place is that, as you point out, `Pointwise` is now heterogeneous in the length of vectors. I'm a bit worried that that might also require K, but it's just a gut feeling. Maybe @jespercockx can tell us more.

**Comment by jespercockx** [comment]
It's possible to prove K for natural numbers, so *in principle* heterogeneous equality between vectors is equivalent to using homogeneous / 'path over' equality. But from a usability perspective I suspect it would be kind of annoying since Agda doesn't allow splitting on reflexive equalities between natural numbers, you have to deal with them yourself.

**Comment by sstucki** [comment]
>> Some universe levels seem to have been dropped.

> Which ones? Could you point them out?

OK, I checked again and I was wrong about levels being dropped, it seems actually the opposite happened: the definition of `Pointwise′` in [v.014](https://github.com/agda/agda-stdlib/blob/v0.14/src/Relation/Binary/Vec/Pointwise.agda#L36) used the same level `ℓ` for `A`, `B` and the relation `_∼_`, whereas the [new definition](https://github.com/agda/agda-stdlib/blob/master/src/Data/Vec/Relation/Pointwise/Inductive.agda#L26) uses separate levels for `A` and `B`. The error message is caused by the overall type of `Pointwise`, which is `Set ℓ`, even though the constructor `_∷_` includes the (potentially bigger) arguments `xs` and `ys` of level `a` and `b`, respectively. To avoid the error, the type of `Pointwise` should be `Set (a ⊔ b ⊔ ℓ)` (analogous to the definition of [Vec.All](https://github.com/agda/agda-stdlib/blob/master/src/Data/Vec/All.agda#L24)) but this breaks some other code downstream.

I'm not actually sure how all of this is related to the `--without-K` option, but I only get the error when I turn it on.

**Comment by jespercockx** [comment]
Well, the reason why this is only a problem when `--without-K` is enabled is that big constructor arguments are only allowed if they are forced and `--without-K` is disabled, see: https://github.com/agda/agda/blob/b7541319c09f308785e8966d734ae9a06cffc19a/src/full/Agda/TypeChecking/Rules/Data.hs#L587 I guess at the time we didn't really know what to do with big forced arguments in the `--without-K` case, so we disabled them altogether in order to be safe.

I've recently got some insight into how to implement a more general criterion for when (big) forced arguments are fine (basically: it should be possible to define the datatype by pattern matching against the indices of the constructors, non-linearity in the indices is only allowed for small variables), but I'm not sure when I will have the time to actually have a shot at implementing this. Stay tuned!

**Comment by MatthewDaggitt** [comment]
> I'm not sure when I will have the time to actually have a shot at implementing this. Stay tuned!

Thanks for the update! Okay as a temporary measure, I've bumped the universe levels up to `a ⊔ b ⊔ ℓ`. This means both files go through with the option `--without-K`. If at some later stage Agda then accepts lower universe levels then we can always lower them again.

**Pull request merged**
