### PR TITLE
Adapt to reflection interface changes

### PR DESCRIPTION
**Pull request by cmcmA20**
Downstream fix, see ~agda/agda#7247~ agda/agda#7322
Do not merge before the parent PR

### CODE REVIEW

**Comment by gallais** [comment]
I'm not a fan of just having a `Bool` there.

**Comment by cmcmA20** [comment]
Yeah, feel free to suggest what other info should be exposed.

**Comment by gallais** [comment]
I don't mean necessarily more information but a type with informative constructor names.

**Comment by MatthewDaggitt** [comment]
Hi @cmcmA20, thanks for the fix! Any chance you could make this against the `experimental` branch rather than the `master` branch? Changes to Agda itself don't usually go on `master`.

**Comment by JacquesCarette** [comment]
This is against milestone Agda-2.6.5 (which doesn't exist) but Agda-2.7 is out. Is this obsolete?

**Comment by cmcmA20** [comment]
@JacquesCarette 
Sorry, I forgot about this PR!
Jesper and Andreas have already merged these changes in #2432.

**Pull request closed without merging**
