### PR TITLE
Codata using sized types and copatterns

### PR DESCRIPTION
**Pull request by gallais**
A first bunch of modules showing how one can use the new style of
defining coinductive data types and how to structure the types and
the relations talking about them.

### CODE REVIEW

**Comment by MatthewDaggitt** [comment]
Looks great! My main question is what are we going to do with the other Codata library?

**Comment by MatthewDaggitt** [comment]
> The other codata library lives in an entirely different namespace so
I don't think it's a problem to keep it around for backwards compatibility.
Plus it is, so far, still needed for things like IO.

Okay, but I feel for v1.0 it then should be extracted out of `Data` into it's own subdirectory? It's pretty confusing for users to have a `Codata` subdirectory and a `Data` subdirectory, but then have lots of codata living in the `Data` directory. Perhaps we could extract it to `MusicalCodata` or `Codata.Musical` while making clear that `Codata` is the more standard implementation?

**Comment by MatthewDaggitt** [comment]
I'll merge it in, and think what to do about the other musical codata later...

**Comment by MatthewDaggitt** [comment]
@gallais , I'm getting the following error when trying to type check `Codata.Covec` with Agda-2.5.4
```
/home/matthew/Code/agda-stdlib/src/Codata/Covec.agda:24,2-26,67
Termination checking failed for the following functions:
  _.replicate
Problematic calls:
  λ { n a .force → replicate (n .force) a }
    (at /home/matthew/Code/agda-stdlib/src/Codata/Covec.agda:26,28-67)
  replicate (n .force) a
    (at /home/matthew/Code/agda-stdlib/src/Codata/Covec.agda:26,45-54)

/home/matthew/Code/agda-stdlib/src/Codata/Covec.agda:37,2-39,67
Termination checking failed for the following functions:
  _.fromColist
Problematic calls:
  λ { x xs .force → fromColist (xs .force) }
    (at /home/matthew/Code/agda-stdlib/src/Codata/Covec.agda:39,28-67)
  fromColist (xs .force)
    (at /home/matthew/Code/agda-stdlib/src/Codata/Covec.agda:39,45-55)
```
Any idea what's going wrong?

**Comment by gallais** [comment]
The termination checker was more liberal in `2.5.3` it seems. Fix coming up (it's a
matter of turning `∞` in the return type into a universally quantified size `i`) after
I've checked the other modules are fine.

**Pull request merged**
