### PR TITLE
Add Algebra.Properties.Semiring.Sum showing mulitplication distributes over sums

### PR DESCRIPTION
**Pull request by Taneb**

### CODE REVIEW

**Comment by Taneb** [comment]
I haven't added this to Everything.agda yet. Is the "correct" way to do that with GenerateEverything.hs, or can I do it manually?

**Comment by MatthewDaggitt** [comment]
I think we should add `-*` prefix onto the end of these names? Otherwise looks great!

**Comment by Taneb** [comment]
> I think we should add `-*` prefix onto the end of these names? Otherwise looks great!

I ended up with `*-distrib?-sum` which feels the most consistent with existing names to me

**Comment by MatthewDaggitt** [comment]
Yup, looks good!

**Pull request merged**
