### PR TITLE
Rename `Relation.Binary.Construct.(Flip/Converse)`

### LINKED ISSUE #1757: Rename `Relation.Binary.Construct.(Flip/Converse)`
to something line `Relation.Binary.Construct.Flip.Ord` and `Relation.Binary.Construct.Flip.EqAndOrd`, following the same pattern as the recently introduced `Algebra.Construct.Flip.Op`.

### PR DESCRIPTION
**Pull request by Saransh-cpp**
Fixes #1757

Renamed -
- `Relation.Binary.Construct.Flip` -> `Relation.Binary.Construct.Flip.Ord`
- `Relation.Binary.Construct.Converse` -> `Relation.Binary.Construct.Flip.EqAndOrd`

A few questions -
- Should I keep the original modules and mark them for deprecation, instead of removing them suddenly?
- Should the `CHANGELOG` entry go in the `Non-backwards compatible changes` section?

Thanks!

### CODE REVIEW

**Comment by MatthewDaggitt** [comment]
Thanks, looks great! Good questions as well :+1: 

> Should I keep the original modules and mark them for deprecation, instead of removing them suddenly?

Yes, please!

> Should the CHANGELOG entry go in the Non-backwards compatible changes section?

If the old modules are kept then it should go under the "[Deprecated modules](https://github.com/agda/agda-stdlib/blob/master/CHANGELOG.md#deprecated-modules)" section

**Comment by MatthewDaggitt** [comment]
@Saransh-cpp the tests are showing there's still a reference to the old names left in.

**Comment by jamesmckinna** [comment]
`GenerateEverything` *should* fix this once the old modules have been marked as DEPRECATED. At the moment, it looks though the generated `EverythingSafe` is picking up the old modules.

**Comment by Saransh-cpp** [comment]
Hmm yes, there are no direct imports of `Relation.Binary.Construct.Converse` in the code at the moment. I traced back the chain of dependencies to check if the modules are being imported anywhere and found nothing.

I think the tests started failing once I removed the contents of `Relation.Binary.Construct.Converse` and `Relation.Binary.Construct.Flip`. Running the tests locally to confirm this.

**Comment by Saransh-cpp** [comment]
Ah, I had to literally use "DEPRECATED" in the file. This works now. Thanks @jamesmckinna @MatthewDaggitt!

**Comment by andreasabel** [comment]
This PR has a filename spelling mistake [src/Relation/Binary/Construct/Flip.Agda](https://github.com/agda/agda-stdlib/pull/1979/files#diff-9e428007b84f4b755958d2f0f21306a9b5f5c119f5d9c0036b4e2c05c456b553) (the uppercase `.Agda` extension`).

As a consequence, I cannot update my working copy to `master` anymore:
```
agda-stdlib[master]$ git pull
Updating df8bdd4ab..8c70a9bfa
error: The following untracked working tree files would be overwritten by merge:
	src/Relation/Binary/Construct/Flip.Agda
Please move or remove them before you merge.
Aborting
```
Fixed by  3041cea05bb3d18169407fb8632a5f9274b6a8c7

**Comment by MatthewDaggitt** [comment]
Eek nice spot. Thank you @andreasabel

**Comment by Saransh-cpp** [comment]
Woops, missed that, thanks!

**Pull request merged**
