### PR TITLE
Added List permutation relation for setoid equalities

### PR DESCRIPTION
**Pull request by lexvanderstoep**
Relates to issue #713

### CODE REVIEW

**Comment by gallais** [comment]
IIUC it's enough for `_~_` to be `Symmetric` for us to get that permutations form a
setoid. We may want to implement the more general definition (the one parametrised
over a mere homogeneous relation) at some point & provide the one parametrised by a
`Setoid` as a special case.

**Comment by lexvanderstoep** [comment]
Would the more general permutation module then be parameterised over a homogeneous relation `_~_` and a corresponding symmetry property `Symmetric _~_`?

**Comment by gallais** [comment]
I wouldn't parametrise it over anything, only adding the `Symmetric` constraint
where it's needed. E.g. `map : (R => S) -> Permutation R => Permutation S` does
not need any extra constraints AFAICT.

**Comment by lexvanderstoep** [comment]
I have added another module for homogeneous relations, and updated the original module to be a special case for setoid equalities. Is this what you were looking for?

**Comment by gallais** [comment]
It is, thanks! I'm not sure however that taking `R` explicitly as a parameter is
really future-proof: if we want to add the `map` function I mentioned earlier then
we need to be able to mention two permutations with two distinct relations.

Map can be useful to for instance convert from a permutation using `Data.Char`'s
`_≈_` (introduced in #727) to one using the equivalent but distinct `_≡_`.

The solution to this issue we have been using in Sublist & friends, is to have a core
module where the datatype is not an infix name & takes all its parameters directly
& then re-export a nicely-named partially applied version for e.g. the setoid special
case.

**Comment by lexvanderstoep** [comment]
IIUC the solution would be to create a core module which takes a heterogeneous relation `R : REL A B r` and implements list permutations using that. Correct?

**Comment by gallais** [comment]
I don't think we can have an heterogeneous module because of `trans`.
I was thinking more along the lines of

```agda
module Data.List.Relation.Binary.Permutation.Homogeneous where

private
  variable
    a r s : Level
    A : Set a

data Permutation (R : Rel {a} A r) : Rel (List A) (a ⊔ r) where
  (...)

↭-refl : ∀ {R : Rel A r} → Reflexive (Permutation R)
(...)

map : ∀ {R : Rel A r} {S : Rel A s} →
      (R ⇒ S) → (Permutation R ⇒ Permutation S)
(...)
```

and then in the setoid module we can define

```agda
_↭_ = Permutation _∼_
```

**Comment by gallais** [comment]
Looks good. I would personally drop the `Perm-` prefix on `refl`, `sym`, `trans`,
etc. as we are clearly only going to be talking about permutations in the
`Data.List.Relation.Binary.Permutation.*` modules.

@MatthewDaggitt we need to clarify the naming convention, I think.

For `Sublist`, we have: [`reflexive`, `refl`, `trans`](https://agda.github.io/agda-stdlib/Data.List.Relation.Binary.Sublist.Heterogeneous.Properties.html#13676)

For `Equality.Setoid` we have: [`≋-refl`, `≋-reflexive`, `≋-sym`, `≋-trans`](https://agda.github.io/agda-stdlib/Data.List.Relation.Binary.Equality.Setoid.html#979)

It makes sense to me that we would have prefixed version of the results in something
as generic as `Data.Nat.Properties` where we have multiple relations which are
reflexive, symmetric, etc. However in something more specific e.g. [`Data.Nat.Divisibility`](https://agda.github.io/agda-stdlib/Data.Nat.Divisibility.html),
that seems more debatable (the module name can always be used to disambiguate, just
like we do for `map`, `zipWith`, etc.).

**Comment by gallais** [comment]
> What would be a reasonable name for Perm-refl and Perm-trans instead?

Aren't they redundant? They are mere aliases to the corresponding constructors.

**Comment by JacquesCarette** [comment]
I must admit that I have in that past used `_\o_` (i.e. composition) instead of `trans` for permutations, and it worked quite nicely. And `!_` for `sym` is quite readable too.

**Comment by lexvanderstoep** [comment]
@gallais Is the pull request ready to be merged?

**Comment by MatthewDaggitt** [comment]
> @MatthewDaggitt we need to clarify the naming convention, I think.
>
> For Sublist, we have: reflexive, refl, trans
>
> For Equality.Setoid we have: ≋-refl, ≋-reflexive, ≋-sym, ≋-trans

Yes we do. I'm not sure how though... The very woolly reasoning that I've been working on is that when we have an obvious symbolic name for the relation such as `_≋_` or `_↭_` which is unlikely to need to be changed then to use them in the name. Otherwise if there is no obvious symbol and hence the relation is named via words such as `Sublist` then it doesn't have the word prepended and users can name the module as they wish. This is open to be changed though!

> @gallais Is the pull request ready to be merged?

Almost. You just need to move the imports inside the module definition as per the [style guide](https://github.com/agda/agda-stdlib/blob/master/notes/style-guide.md). The exception is `Relation.Binary` which will need to remain above the module declaration. After that I'll merge this in. Thanks @lexvanderstoep!

I'll deal with reimplementing `Permutation.Inductive` in terms of `Permutation.Setoid` in a separate PR.

**Comment by gallais** [comment]
Nice. Thanks @lexvanderstoep!

**Pull request merged**
