### PR TITLE
Fixes #2166 by fixing names in `IsSemilattice`

### LINKED ISSUE #2166: Problems with change of `Semilattice` operation name
First issue with RC 1. Changelog doesn't mention that the name of the operation in `Semilattice` changed from `_∧_` to `_∙_`.

More problematically the names in `IsSemilattice` have not been changed :cry: 

https://github.com/agda/agda-stdlib/blob/a7d23029ac94ba446d2cf2a6f4bf3859d7aa9506/src/Algebra/Lattice/Structures.agda#L39

### PR DESCRIPTION
**Pull request by MatthewDaggitt**

### CODE REVIEW

**Comment by jamesmckinna** [comment]
This looks fine, but I'd maybe wait on a review from @Taneb ?

**Comment by Taneb** [comment]
To close #2166 the changes to the `Semilattice` bundle also need to be described, I think

**Comment by jamesmckinna** [comment]
And again: what is the name of the operator symbol? My `emacs` is rendering it as a 'thick' dot, not a 'thin' one...

**Comment by MatthewDaggitt** [comment]
> To close https://github.com/agda/agda-stdlib/issues/2166 the changes to the Semilattice bundle also need to be described, I think

Yes, nice spot! Have done so.

> And again: what is the name of the operator symbol (in Algebra.Lattice.Bundles)? My emacs is rendering it as a 'thick' dot, not a 'thin' one...

`\.`

**Review by jamesmckinna — APPROVED** [review]
I approve the changes without further ado. 
But at some point downstream should we not also return to the question of the orderings induced by any such otherwise ostensibly direction-uncommitted `(Raw)Magma` operation (associative, idempotent, etc. or otherwise) as in `Algebra.Definitions.RawMagma` cf. #2115 / #679  as well as @Taneb's #2138 ...?

UPDATED: and in the light of #3030 / #3031 ?

**Comment by MatthewDaggitt** [comment]
> But at some point downstream should we not also return to the question of the orderings induced by any such otherwise ostensibly direction-uncommitted (Raw)Magma operation (associative, idempotent, etc. or otherwise) as in Algebra.Definitions.RawMagma cf. https://github.com/agda/agda-stdlib/issues/2115 / https://github.com/agda/agda-stdlib/issues/679 as well as @Taneb's https://github.com/agda/agda-stdlib/issues/2138 ...?

Yup definitely.

**Pull request merged**
