### PR TITLE
add property Fin0↔⊥

### PR DESCRIPTION
**Pull request by JacquesCarette**
This is another useful piece of showing that finite types are a skeleton of the semiring of types. I've needed it independently too.

### CODE REVIEW

**Comment by gallais** [comment]
Should this (and the content of #1393) go into `Data.Fin.Algebra`
just like their equivalents go into `Data.(Sum/Product).Algebra`?

**Comment by JacquesCarette** [comment]
Good question. The Bundles most likely should. I don't know about the pieces though.

**Comment by MatthewDaggitt** [comment]
Hmm I don't think I'd be in favour of putting them there, as the results do not have anything to do with the algebra hierarchy...
`Fin` is not a binary op and therefroe does not form any algebraic structures (e.g. magma/semigroup). Personally, I'm happy with their current location.

**Comment by JacquesCarette** [comment]
In which case, I think this is ready to go, same as with #1393.

**Pull request merged**
