### PR TITLE
[ new ] fromBool : Bool → A → A ⊎ A

### PR DESCRIPTION
**Pull request by gallais**

### CODE REVIEW

**Comment by JacquesCarette** [comment]
This is really one of the directions from the proof of `Inverse (Bool x A) (A ⊎ A)`. And calling it `fromBool` is perhaps sub-optimal, seen in that light?

**Comment by gallais** [comment]
I used the uncurried version together with `partitionSumsWith` so I would be happy
to implement both directions using `Product`. :D

**Comment by MatthewDaggitt** [comment]
What's the status of this? Is this ready or does it need a change?

**Comment by gallais** [comment]
No hurry for this one either, I ended up using something else in the end.

**Comment by laMudri** [comment]
Wouldn't it make more sense to call this function `fromBool′`, and have one of the following for `fromBool`?

```agda
fromBool₀ : {A : Bool → Set a} (b : Bool) → A b → A true ⊎ A false
fromBool₁ : {A : Set a} {B : Set b} (b : Bool) → (if b then A else B) → A ⊎ B
```

**Comment by MatthewDaggitt** [comment]
@gallais as you ended up using something else, I'm going to close this for now? Feel free to reopen and bring up to date if you'd like it in.

**Pull request closed without merging**
