### PR TITLE
Make sure RawRing defines rawRingWithoutOne

### PR DESCRIPTION
**Pull request by Taneb**

### CODE REVIEW

**Review by gallais — COMMENTED** [review]
Can we please get a CHANGELOG entry?

**Comment by Taneb** [comment]
I think tomorrow I'm going to do a more thorough survey for what inherited definitions might be missing

**Comment by jamesmckinna** [comment]
See also #1917 and the discussion there about 'missing' exports...

**Comment by jamesmckinna** [comment]
Did your investigations @Taneb yield any more items to add to this PR, or should we wrap this up now?

**Comment by Taneb** [comment]
I drew a big graph of how everything in `Algebra.Structures` relates, and then... never did anything with it. This can be merged as-is, I'll make another PR if I do a more exhaustive check

**Comment by Taneb** [comment]
I don't think a changelog entry is necessary, `RawRingWithoutOne` was only added in this release

**Pull request merged**
