### PR TITLE
Moving generalised arithmetic into its own file

### PR DESCRIPTION
**Pull request by MatthewDaggitt**
Hopefully self explanatory. In my opinion it's not a core part of `Data.Nat` and now that @gallais has fleshed it out it deserves its own top-level module. This also helps keep `Data.Nat.Properties` tidier.

### CODE REVIEW

**Comment by gallais** [comment]
Aren't all `distrib` lemma of the form `x op1 (y op2 z) = (x op1 y) op2 (x op1 z)`? In which case it's not a very appropriate name for `x ^ (m + n) = x ^ m * x ^ n`. It might be better to present it as a monoid morphism between `(Nat, +)` and `(Nat, *)`.

**Comment by MatthewDaggitt** [comment]
Hmm that's true. I was going under the argument that you **are** distributing `_^_` over `_+_`, it's just that it happens to turn into a `_*_` when you do so. 

I'm open to suggestions! We could always go for the full expression? `x^[m+n]≡[x^m]*[x^n]`. A bit long though... Or `^-distribˡ-+-*`? If you were going to present it as a monoid morphism how would you do it?

There are some similar naming issues with some of the min-max and subtraction operators, e.g.:
```agda
∀ x y z → x ∸ (y ⊔ z) ≡ (x ∸ y) ⊓ (x ∸ z)
```
so whatever we decide, it needs to generalise.

**Comment by gallais** [comment]
I like this one `^-distribˡ-+-*` because the usual `distrib` then look like a shorthand where you shrink e.g. `+-+` to `+`. I suppose the packed notion of Monoid morphism (including the fact that it respect neutral elements) should go in [`Algebra.Morphism`](https://agda.github.io/agda-stdlib/Algebra.Morphism.html) and the instance could be called e.g. `+-*-monoid-morphism`.

**Comment by MatthewDaggitt** [comment]
> I like this one ^-distribˡ-+-* because the usual distrib then look like a shorthand where you shrink e.g. +-+ to +.

Sounds good, we'll go with that one then. As you say, it gives us room (in naming terms) for later formalising the monoidal view.

**Pull request merged**
