### PR TITLE
[ fix #12 ] Basic operations on rationals

### PR DESCRIPTION
**Pull request by gallais**
* Brought the branch up to speed
* Kept the full proof that the numerator and the denominator are coprime rather than a `True`d version
* But made it irrelevant!

### CODE REVIEW

**Comment by MatthewDaggitt** [comment]
Does using irrelevance mean that normalisation now performs better? I remember you saying in #12 that it was almost unusable?

**Comment by gallais** [comment]
It's a bit better but it's still super slow. We should still have a look at Ulf's agda-prelude.

**Comment by Zambonifofex** [comment]
Hello, I’m new to Agda, so correct me if I’m wrong, but isn’t it redundant to have both `_÷_` and `mkℚ`?

Can’t you make the `isCoprime` field in `ℚ` somehow be implicit in its constructor, and then simply name the constructor `_÷_`?

Also, interesting that I have come to need these operations (in particular subtraction) just yesterday, and now they are planned to be added to the stdlib!

Although, since they aren’t out yet, I might need to copy them into my module (modifying it accordingly to work with my version of the stdlib).

**Comment by MatthewDaggitt** [comment]
Hi @Zambonifofex, it's great that you're interested!

> Can’t you make the isCoprime field in ℚ somehow be implicit in its constructor, and then simply name the constructor _÷_?

Unfortunately I'm not so sure about this. It seems like creating the proof is most of the "hard work" in the current formalisation, and therefore it seems unlikely to be inferable in general by Agda. I may be mistaken though. Do you have a concrete suggestion?

It's still some debate to be had on how we're going to implement rationals, and this part of the library may change a bit in the near future. Do feel free to lift whatever code you like the look of though in the mean time!

**Comment by Zambonifofex** [comment]
Hello, @MatthewDaggitt.

I’m not sure you understood. I’m not saying that it would be easily inferrable, but, right now, in this pull request, `_÷_` is defined (effectively) as `(n ÷ suc d) {c} = mkℚ n d (toWitness c)` (i.e. about the same as `mkℚ`, but with its parameter marked as inferrable). All I’m saying is that it feels redundant to have both.

Although, as I just noticed (derp), `_÷_` subtracts one from its parameter before passing it to `mkℚ`. Either way, it’s not like “decrementing by one” is an involved operation.

That is, to summarize my thoughts, I’d say *get rid of `_÷_` and optionally make `isCoprime` inferrable* (since `mkℚ` and `_÷_` are effectively the same operation).

Also, As I copied the operations into my module, I was able to avoid repeating `eq` twice in `normalize`, but not `pr`. I was wondering if someone who is more familiar with Agda than I am would be able to do it, though.

**Comment by MatthewDaggitt** [comment]
While trying to help @Zambonifofex's (https://lists.chalmers.se/pipermail/agda/2018/010427.html) I noticed that the previous definitions of `_+_` and `_*_` were a bit screwy. `_+_` did a weird `with` check and `_*_` had some unnecessary case splits. I've updated them both to their more natural definitions.

I've also made the non-zero proof of `norm-mkℚ` both implicit and irrelevant.

**Pull request merged**
