### PR TITLE
Add `flip′` to `Function.Base`

### PR DESCRIPTION
**Pull request by XiaohuWang0921**
Add a non-dependent version of `flip` to `Function.Base`

### CODE REVIEW

**Comment by Taneb** [comment]
I'm not opposed to adding this, but do you know of a situation where the dependent version doesn't work?

**Comment by XiaohuWang0921** [comment]
It happened when I tried to `flip` an overloaded constructor in a complex enough context. My original code looks something like this:
```agda
open import Data.Nat.Base
open import Data.Fin.Base
open import Data.Vec.Base hiding (map; alignWith)
open import Data.Maybe.Base
open import Data.These.Base hiding (map; alignWith)
open import Function.Base

data Lazy (n : ℕ) : Set where
  var : Fin n → Lazy n
  abs : Lazy (suc n) → Lazy n
  app : ∀ {k} → Vec (Lazy n) k → Lazy k → Lazy k → Lazy n

data Dummy : Set where
  app : Dummy

private
  variable
    m n k : ℕ

subs : Vec (Lazy n) m → Lazy m → Lazy n
subs = {!!}

allStep : Vec (Lazy n) k → Maybe (Vec (Lazy n) k)
allStep = {!!}

step : Lazy n → Maybe (Lazy n)
step (app shared s @ (var _) t) = alignWith (foldWithDefaults shared t (flip {-flip′-} app s)) (allStep shared) (step t)
step _ = {!!}
```
And Agda complains about unsolved constraints at `flip` (I am using version 2.6.2.2). Remove the `Dummy` type, and the complaint disappears; try `flip app` in a simpler function, and the complaint also disappears.

**Comment by Taneb** [comment]
OK, great! Could you add a note about this to the changelog?

**Comment by MatthewDaggitt** [comment]
Merging in, thanks for the PR @XiaohuWang0921

**Pull request merged**
