### PR TITLE
add `Maybe` type for Haskell interop

### PR DESCRIPTION
**Pull request by Zambonifofex**
Since Haskell FFI pragmas were removed from `--safe` modules, the `Maybe` type from `Data.Maybe` doesn’t map to Haskell’s `Maybe` type anymore. Since some libraries that interoperated with Haskell (e.g. @gallais’s “sized IO” library) depended on the mapping, they stopped succeeding to compile. This pull request offers an alternative `Maybe` type that does map to Haskell `Maybe` that such libraries can use.

### CODE REVIEW

**Comment by MatthewDaggitt** [comment]
Hmm that sounds like an unfortunate consequence of the revamp of `--safe`. Having two versions of `Maybe` isn't ideal but this is probably the best solution to the problem at the moment.

Won't it prevent the Sized IO library from using any of the associated functions/properties of `Maybe` as well or does it not use any of them?

**Comment by gallais** [comment]
> Won't it prevent the Sized IO library from using any of the associated functions/properties of Maybe as well or does it not use any of them?

The plan is to use that `Foreign` maybe only for the FFI and to convert it as soon
as possible to a `Data.Maybe` one.

**Comment by Zambonifofex** [comment]
I don’t think adding conversion functions for `Pair` makes sense to do in this pull request, but if you reckon it’s a good idea, I can add conversion functions for `Maybe`.

**Comment by gallais** [comment]
> I don’t think adding conversion functions for Pair makes sense to do in this pull request

Fair enough.

> but if you reckon it’s a good idea, I can add conversion functions for Maybe.

I think it'll be useful. I have just added similar functions to agda-sizedIO (still
not pushed because of agda/agda#3696 breaking things somewhere else) and it was
immediately useful.

I structured it like this so that I could use the same names `(from/to)Foreign`
for the conversion functions for all of the datatypes crossing the FFI boundary:

```agda
module Foreign.Haskell where

(...)

module X where

  import Data.X.Base as X
  data X (...)

  fromForeign : X -> X.X
  toForeign : X.X -> X
```

**Comment by Zambonifofex** [comment]
I’ve thought about this for quite a while now, and I figured it makes more sense to add `{to,from}Foreign{Pair,Maybe}` (only for `Maybe` in this pull request). I say this because I feel like being able to use the types (and conversion functions) with a single `open` statement ought to be more convenient for people than having to open an inner module too. In addition, it’s also more backward compatible, since `Pair` was preexistent and not in an inner module.

Does anyone disagree? If no‐one does, I’m going to go ahead on commit changes to my branch that follow this idea tomorrow.

**Comment by gallais** [comment]
If you want the types to be available by simply `open import Foreign.Haskell`,
you can `open X using (X; [CONSTRUCTORS]) public`. The advantage of a short name
inside of a module whose name you can use to disambiguate it is that if you only
care about one of these you can open the module and use the short name. And otherwise 
you use the prefixed name which is basically just as long as the long name.

That's why we have `map` in all the `Data.X` modules rather than various `mapX`.

**Comment by Zambonifofex** [comment]
I realize that, but my rationale is that there is not enough ergonomic benefit to the module version.

That is, under that approach, if someone has `open import Foreing.Haskell` in their file already, in order to use `{to,from}Foreing`, they will either need to qualify it (e.g. `Maybe.fromForeing`), or take the extra action of opening the inner module (e.g. `open Maybe`).

Under my approach, if someone wants to use `{to,from}Foreing`, they will either need to use the full name (e.g. `fromForeingMaybe`), or take the extra action of renaming the function (e.g. `renaming (fromForeingMaybe to fromForeing)`).

Under both approaches, the “default” is to have to make the converted type explicit, but the user can take an extra action if they want to use the short name.

Of course, I understand that `open Maybe` is shorter and less repetitive than `renaming (toForeingMaybe to toForeing ; fromForeingMaybe to fromForeing)` (and maybe that’s a convincing enough reason), but I just find it kinda awkward how users would only need to use these inner modules for the conversion functions (since the outer module would re‐export the types, constructors, and fields anyway).

I guess an approach that doesn’t really have any of these disadvantages would be to have `{Pair,Maybe}Convertion` modules, and put only the convertion functions inside them. Since there are no other functions that will be defined for these types (since they should be defined for their `Data.X` variants instead), there is no danger of non‐convesion functions needing to be defined.

What do you reckon? Does this sound like a good enough approach?

**Comment by Zambonifofex** [comment]
@gallais, @MatthewDaggitt, what do you guys think? Do you reckon that you like my `{Pair,Maybe}Convertion` inner modules idea? If you don’t, I’d be glad to comply with whatever you guys might think is best.

**Comment by MatthewDaggitt** [comment]
So my personal preference would be to have top level modules `Foreign.Haskell.Maybe` and `Foreign.Haskell.Pair` etc. which would circumvent this whole problem. This could be made backward compatible by having `Foreign.Haskell` re-export the contents of all sub-modules with suitable renaming in place. Then (I hope!) everyone is happy!

**Comment by MatthewDaggitt** [comment]
@Zambonifofex do you think you'll have time to this in the next week or so before v1.1?

**Comment by Zambonifofex** [comment]
Hello! Sorry for not having taken action, it’s just that I’m not really sure about how to proceed. (I kinda thought someone would say something before, but no‐one really did, and then I forgot about it.)

Either way, I feel like I have plenty of time, I just don’t know how to go about doing it. I feel like the best approach is to close this specific pull request, and then open a new one for separating `Foreign.Haskell` into multiple modules. Does that sound like it makes sense to you?

**Comment by MatthewDaggitt** [comment]
> Hello! Sorry for not having taken action, it’s just that I’m not really sure about how to proceed. (I kinda thought someone would say something before, but no‐one really did, and then I forgot about it.)

> Either way, I feel like I have plenty of time, I just don’t know how to go about doing it. I feel like the best approach is to close this specific pull request, and then open a new one for separating Foreign.Haskell into multiple modules. Does that sound like it makes sense to you?

That's okay, no worries! So the plan is to create two modules `Foreign.Haskell.Maybe` and `Foreign.Haskell.Pair`. Within both of these, the conversion functions will be called `toForeign` and `fromForeign`. The module `Foreign.Haskell` should then re-export everything, renaming `toForeign` to `to/fromForeignMaybe` and `to/fromForeignPair`. 

Hope that helps, feel free to ask more questions :+1:

**Comment by MatthewDaggitt** [comment]
Okay implemented the changes. @gallais  can you take a quick look to see if it's all okay?

**Comment by gallais** [comment]
I have just realised that we do not need to redefine `Maybe` (or any other
inductive type for that matter), we can use `abstract` to generate a stuck
name equal to `Maybe`, throw in the trivial conversion functions in the
same `abstract` block before that name is sealed and add compiler directives
to that alias like so:

```
private
   variable
     a : Level
     A : Set a

import Data.Maybe as Data

abstract

  Maybe : Set a → Set a
  Maybe = Data.Maybe

  fromForeign : Maybe A → Data.Maybe A
  fromForeign x = x

  toForeign : Data.Maybe A → Maybe A
  toForeign x = x

{-# FOREIGN GHC type AgdaMaybe l a = Maybe a #-}
{-# COMPILE GHC Maybe = data AgdaMaybe (Just | Nothing) #-}
```

**Comment by gallais** [comment]
Should work for pairs too:

```agda
private
   variable
     a b : Level
     A B : Set a

import Data.Product as Data

abstract

  Pair : Set a → Set b → Set (a ⊔ b)
  Pair = Data._×_

  fromForeign : Pair A B → A Data.× B
  fromForeign x = x

  toForeign : A Data.× B → Pair A B
  toForeign x = x

{-# FOREIGN GHC type AgdaPair l1 l2 a b = (a , b) #-}
{-# COMPILE GHC Pair = data MAlonzo.Code.Foreign.Haskell.AgdaPair ((,)) #-}
```

**Comment by MatthewDaggitt** [comment]
@gallais all good?

**Comment by gallais** [comment]
I did not realise you could break up an `abstract` block into multiple ones without
losing the computational behaviour of the things abstracted over.

**Comment by MatthewDaggitt** [comment]
> I did not realise you could break up an abstract block into multiple ones without
losing the computational behaviour of the things abstracted over.

Yup, multiple blocks within the same scope all share the same "abstraction space".

**Comment by gallais** [comment]
Sorry, my suggestion to use `abstract` seems to have broken compilation:

> Haskell data types can only be given for data or record types.

**Comment by MatthewDaggitt** [comment]
Ah, okay I'll revert them back before I release. Thanks for the heads up :+1:

**Comment by Zambonifofex** [comment]
Hello! I wanted to be able to apologize for having taken so long, and end up not having done what I promised to. I feel like I was irresponsible, and that I ended up letting you down.

Either way, I'm glad that this seems to have been taken care of appropriately. Thanks for your amazing work, and the splendid library! 😊

**Comment by MatthewDaggitt** [comment]
> Sorry, my suggestion to use abstract seems to have broken compilation:

Fixed.

> Hello! I wanted to be able to apologize for having taken so long, and end up not having done what I promised to. I feel like I was irresponsible, and that I ended up letting you down.

No worries at all @Zambonifofex. Thank you for being proactive and making the suggestion in the first place!

**Pull request merged**
