### PR TITLE
[ fix #393 ] move nat-computed levels to their own module

### LINKED ISSUE #393: Nat-computed levels introduce conflict with non-standard natural BUILTINs
Having Nat-computed levels makes it impossible to use huge portions of the standard library while using your own version of natural numbers, because you'll get an error from the two conflicting BUILTINs for Nat. 

I'd suggest putting this code elsewhere in the standard library, say in `Level.FromNat`. 

See the discussion at 3fa7e0f06dba3af2c726f8742a9a50a07341f402.

### PR DESCRIPTION
**Pull request by wenkokke**

### CODE REVIEW

**Comment by gallais** [comment]
Don't forget to edit the `CHANGELOG` which, at the moment, states that these functions
have been added to `Level`.

As for the name, as I mentioned in my edit (sorry, I should probably have posted another
comment, it would have been more visible) it may be worth calling the module `Level.Literals`
and provide an instance of [`fromNat`](https://agda.readthedocs.io/en/v2.5.4.1/language/literal-overloading.html?highlight=fromnat) (the builtin is in `Agda.Builtin.FromNat`).

Why `Literals`? Because then we can have a uniform naming scheme for the similar modules
we can add for `Nat`, `Integer`, `Rational`, `Fin`, etc. which may provide `fromNat` but also
`fromNeg`.

**Comment by wenkokke** [comment]
Wasn't there something about not using the `FromNat` class in the standard library? I can't find any existing instances of `FromNat` anywhere in the current standard library, so while adding one is tempting, I think it might not be taken well?

**Comment by gallais** [comment]
I don't remember such a decision. I think we have just been lagging behind just like
with `Data.Float` which we added way after it had landed in Agda IIRC.

It's true that we don't use instance search mostly because it would not be backwards
compatible and I'm not sure it interacts well with post-projections.

E.g. this is invalid Agda code (you have to use `.R.proj`):

```agda
record R : Set₁ where
  field proj : Set
open R {{...}} public

r : R
r .proj = {!!}
```

However these `fromX` instances don't cause these issues and do provide a useful
overloading for literals. The fact they would be hidden in their own independent
modules that users can ignore if they want to makes me think it would be ok.

**Comment by wenkokke** [comment]
@gallais So, including something like the following?

```agda
LevelNat : Number Level
LevelNat .Number.Constraint _ = ⊤
LevelNat .Number.fromNat    n = # n
```

@andreasabel I vaguely remember you being opposed to using `Agda.Builtin.FromNat` in the standard library, could you tell us if this is the case?

**Comment by gallais** [comment]
Using a record would look cleaner imo

```agda
instance

  LevelNat : Number Level
  LevelNat = record
    { Constraint = const ⊤
    ; fromNat    = #_
    }
```

**Comment by gallais** [comment]
It is useless if it is not an instance, is it not?

**Comment by wenkokke** [comment]
You can import the "instance" and then assign it to a proper instance yourself, i.e.

```agda
import Level.Literals
instance LevelNat = Level.Literals.LevelNat
```

As far as I know, this is the recommended practice. If you search the standard library, then you will not find a single instance declaration anywhere.

**Comment by MatthewDaggitt** [comment]
> You can import the "instance" and then assign it to a proper instance yourself
>....
> As far as I know, this is the recommended practice. If you search the standard library, then you will not find a single instance declaration anywhere.

This is indeed the current policy (see #33).  It might well be a throwback to the when the instance feature wasn't well developed, however I've encouraged it on the grounds that the standard library tries to keep proofs as explicit as possible. The overhead of `instance LevelNat = Level.Literals.LevelNat` probably isn't that great, and at least warns the reader that there is some instance magic about to happen...

**Comment by wenkokke** [comment]
See, I knew there was an issue out there somewhere which I'd filed 😂

**Comment by MatthewDaggitt** [comment]
> I suppose all that leaves open is the question, do we use Agda.Builtin.FromNat?

No strong opinion. If you think someone 't  find it useful and you don't mind adding it, then go for it. Otherwise I'm happy to merge this as is.

**Comment by wenkokke** [comment]
I've added an instance of `Number Level`, because why not.

**Comment by MatthewDaggitt** [comment]
Great, thanks! Merging in now.

**Comment by MatthewDaggitt** [comment]
After merging, I've renamed `LevelNat` to `Levelℕ` as I've just remembered we don't tend to use `Nat` much in the standard library.

**Pull request merged**
