### PR TITLE
[ new ] Without Loss Of Generality

### PR DESCRIPTION
**Pull request by gallais**
Thinking about #444 and the fact that some of the proofs felt very symmetric,
I started thinking about "without loss of generality".

This is what I came up with. With this I am able to drop the `private` proof in
#444 and refactor `*-distribˡ-∣-∣` this way:

```agda
*-distribˡ-∣-∣ : _*_ DistributesOverˡ ∣_-_∣
*-distribˡ-∣-∣ a = wlog ≥-total (comm⇒sym[distribˡ] {_•_ = _*_ } ∣-∣-comm a) $′ λ m n m≤n → begin
    a * ∣ m - n ∣     ≡⟨ cong (a *_) (m≤n⇒∣n-m∣≡n∸m m≤n) ⟩
    a * (m ∸ n)       ≡⟨ *-distribˡ-∸ a m n ⟩
    a * m ∸ a * n     ≡⟨ sym $′ m≤n⇒∣n-m∣≡n∸m (*-monoʳ-≤ a m≤n) ⟩
    ∣ a * m - a * n ∣ ∎
```

There are probably other refactoring opportunities out there.

### CODE REVIEW

**Comment by MatthewDaggitt** [comment]
Wow, that's really quite clever. I can think of several places in my own projects where that would be useful.

**Comment by JacquesCarette** [comment]
This does seem really cool. Is it related to Bob Atkey's work on WLOG ?

**Comment by gallais** [comment]
I had a look at [Bob's "Generalising Abstraction" talk](https://bentnib.org/posts/2016-01-26-obt.html) which I assume is what
you are referring to. This is what I understand of it (ping @bobatkey):

For the most part, I think Bob talks about semantical tools which derive, via
parametricity, invariance results "for free". If you manage to internalise that
knowledge then inside your language you cant get away with assuming
something WLOG.
Alternatively if you have a meta-language of tactics you can internalise some
knowledge about symmetry in the meta-language rather than the language itself.
Bob cites John Harrison's WLOG tactic (I'm going to read that this afternoon)
as an example.

This PR does not do anything that fancy, it records the WLOG pattern thus
letting users make its use explicit. However they don't get anything for free:
they need to have proven that the `Relation` they are introducing a proof
of is `Total`, and that their goal is `Symmetric`.

The essence of the idea is in `Relation.Binary.Consequences`:

```agda
wlog : Total _R_ → Symmetric Q →
       (∀ a b → a R b → Q a b) →
       ∀ a b → Q a b
wlog r-total q-sym prf a b with r-total a b
... | inj₁ aRb = prf a b aRb
... | inj₂ bRa = q-sym (prf b a bRa)
```

The rest of the PR is just specializations of this one idea to make it easier
to use (with a goal talking about the result of a commutative function, with
a goal that looks like `DitributeOver`, etc.)

**Comment by JacquesCarette** [comment]
Yes, that is what I was referring to. And I had forgotten John Harrison's work on same...

Note that your version relies on `Total`, which is a bad name for that property, as @WolframKahl has pointed out elsewhere. Wikipedia calls in 'connex' (https://en.wikipedia.org/wiki/Connex_relation).

This ought to generalize quite a lot. The basic shape is that you have a property Q which is 'easy' to prove under some invariant R, and you have a normal form for all elements of your space that respect R, along with computable means of going between a and its normal form (and back), you can apply WLOG.

Above, r-total is a decision procedure for 'connex' of R, prf is invariant under R, and id/q-sym are the maps 'back' from normal form.

**Comment by gallais** [comment]
We should remember to update the proof of `*-distribˡ-∣-∣` to take advantage of `wlog`.

**Pull request merged**
