### PR TITLE
[ fix #683 ] re-export specialised versions of the constructors

### LINKED ISSUE #683: Making sublists heterogeneous introduces an ugly unsolved meta
Sublists do not work as well as before since they were made specializations of heterogeneous sublists (#562).  Here is a regression:
```agda
open import Data.List.Base using (List; _∷_)
open import Data.List.Relation.Binary.Sublist.Propositional using (_⊆_; _∷ʳ_)
open import Data.List.Relation.Binary.Sublist.Propositional.Properties using (refl)

-- Works, but ugly

wk1 : ∀{a}{A : Set a} {x : A} {xs : List A} → xs ⊆ x ∷ xs
wk1 {A = A} = _∷ʳ_ {A = A} _ refl

-- Intended use by library designer, but fails.

fails : ∀{a}{A : Set a} (x : A) {xs : List A} → xs ⊆ x ∷ xs
fails x = x ∷ʳ refl  -- Agda cannot infer parameter A of ⊆
```
The unsolved parameter `A` also sabotages the intended infix use of the constructor which used to be named `skip`.

### PR DESCRIPTION
**Pull request by gallais**
Do we need to also re-export specialised versions of the functions?!

### CODE REVIEW

**Comment by MatthewDaggitt** [comment]
Yup they do. The following code gives an unsolved meta even after the above changes:
```agda
test : ∀ {a} {A : Set a} (xs : List A) → [] ⊆ xs
test xs = minimum xs
```

**Comment by gallais** [comment]
I've pushed a potential fix which doesn't force us to write new type annotations for
each function we want to re-export. If we are happy with this design, I'll also
modify the `.Properties` files.

**Comment by MatthewDaggitt** [comment]
Hmm it's not pretty but I guess better than nothing giving we're working against a deadline. We can always work out a better way of doing it later. Go for it :+1:

**Comment by MatthewDaggitt** [comment]
Fixing this now. There's a few more bugs in there (e.g. filter-takewhile) is still asking for a trivial reflexivity proof.

**Comment by MatthewDaggitt** [comment]
Actually there were several more proofs that didn't quite export properly from `Heterogeneous` to `Setoid` (e.g. `map`). In the end I just went and rewrote the file out for `Setoid.Properties`. It's much more readable this way for users as well because to be honest translating the types of the proofs in `Heterogeneous.Properties` in your head isn't much fun.

I've also merged `Homogeneous.Properties` into `Heterogeneous.Properties` as there is no top level `Homogeneous` file and the distinction between the two doesn't make any difference to users.

Finally I've also followed the conventions of the `Equality` modules by having the top level module export the relational properties rather than the actual properties. All in all hopefully much easier to use.

**Comment by gallais** [comment]
Thanks! I was at <Programming> so I didn't have much time to look at this (did the
sorted list thing because someone asked me a pointed question about formalising
something involving them in Agda).

**Pull request merged**
