### PR TITLE
Wrapping Comments & Fixing Code Delimiters

### PR DESCRIPTION
**Pull request by ThinkDumbIndustries**
I have made several refactoring changes, focusing on improving code readability and ensuring consistency:

1. Wrapping comments to adhere to the recommended 72 character limit. I exercised caution to avoid unnecessarily harming readability and only made changes when it enhanced code legibility, e.g. skipping single lines comments that go over the limit by only a few characters.
2. Code delimiters: I fixed inconsistent code delimiters, typically missing just a handful of dashes.
3. I removed a single commented-out `import` line from `Relation/Binary/Reasoning/Setoid.agda` that seemed to be leftover from previous work

I have not changed the content itself, only the formatting. I believe these changes improve the quality and consistency of the library. I wrote a small script to exhaustively search the codebase for such instances. As this is my first contribution, I would be particularly grateful for feedback and guidance. Do let me know if any further adjustments or modifications are necessary.

### CODE REVIEW

**Comment by MatthewDaggitt** [comment]
Thanks for the great first contribution! Looks good to me. No comments looking through it!

**Comment by jamesmckinna** [comment]
So... albeit against @MatthewDaggitt 's approval (and he takes precedence):

* even if the style guide recommends 72-character width for the *text* of comments...
* the 'comment' line dividers should, IMHO, be kept at 80 character width, to provide a 'hard' limit for comment lines which overstep the 72 limit by 0<chars<=8 ... to avoid unnecessary/adverse libe-breaking?

I may be a formatting outlier... given that my emacs buffers are typically 96 characters wide.

**Comment by ThinkDumbIndustries** [comment]
It does seem to me like breaking up single line comments might be excessive in some cases, e.g. `Data/Vec/Functional/Properties.agda` line 75 which is 73 characters long. I might suggest something along the lines of:
- If a comment fits in a single line, it can be up to 80 characters
- If it does not fit, break lines after at 72 characters for the entire comment block

**Comment by ThinkDumbIndustries** [comment]
Curiosity got to me so I wrote another little script to count line dividers, categorised by number of dashes. Here are the results for all `.agda` files in the `src` directory as it currently stands in the repository:
```
Dash Count Summary:
63 dashes:    2 occurrences
70 dashes:   72 occurrences
71 dashes:   23 occurrences
72 dashes: 5141 occurrences
73 dashes:   19 occurrences
78 dashes:   44 occurrences
80 dashes:   11 occurrences
81 dashes:    1 occurrences
```
And after my last commit:
```
Histogram Summary:
70 dashes:   10 occurrences
72 dashes: 5303 occurrences
```
These dividers with 70 dashes occur when dividers are in a module where everything is indented by two spaces, e.g. in `Text/Format/Generic.agda`.

**Comment by jamesmckinna** [comment]
Fascinating stats! Interesting insight (perhaps only for software archaeologists) as to inconsistencies in the evolution of the library...

**Review by gallais — APPROVED** [review]

**Comment by MatthewDaggitt** [comment]
I think this is an improvement as is, so am going to merge in. I welcome a more nuanced discussion of the comment styling policy if someone wants to open a specific issue.

**Pull request merged**
