### PR TITLE
[ fix #540 ] updateAt and extra Properties on List.All

### PR DESCRIPTION
**Pull request by gallais**

### CODE REVIEW

**Comment by gallais** [comment]
I have the impression that part of the problem is, we start from a 0.17 CHANGELOG.
So I still need to clean that up.

**Comment by gallais** [comment]
Can you please have a look @ajrouvoet. Is this all of the content?

**Comment by MatthewDaggitt** [comment]
Thanks for rescuing this @gallais!

**Comment by ajrouvoet** [comment]
Indeed, sorry I didn't get back to it. I'm rebasing the monotone predicate monad PR though, which is what this was prep for.

**Pull request merged**
