### PR TITLE
Automated proof of permutation for Fin with instance resolution.

### PR DESCRIPTION
**Pull request by xekoukou**
There might be a way to simplify this. For now, it works.

After this, I will automate the proof for equality up to permutation for the ```Data.Table``` structure.

Since ```List``` and ```Vec``` construct a Table structure , this will also define an equality for them up to permutation.

### CODE REVIEW

**Comment by MatthewDaggitt** [comment]
Thanks for the PR. If you don't mind I'd prefer that we first resolve #559 before merging in anything like this in? Otherwise we're going to end up with stray instances floating around everywhere.

On a separate note should permutation proofs be in `Data.Fin.Instance`?

**Comment by xekoukou** [comment]
Ok , I am waiting for the resolution of #559. I do not like that permutation operations are in Data.Fin.Instance either. Should they be in Data.Fin.Instance.Permutation ? That would make more sense.

**Comment by MatthewDaggitt** [comment]
> Data.Fin.Instance either. Should they be in Data.Fin.Instance.Permutation ? That would make more sense.

Yes, that sounds better.

**Comment by MatthewDaggitt** [comment]
Closing for the moment as we still haven't made much progress on #559 in two years, and realistically I'm not sure we want to be going down the path of redefining every relation using instance arguments.

**Pull request closed without merging**
