### PR TITLE
Indexed binary trees

### PR DESCRIPTION
**Pull request by alexarice**
Adds whatever the equivalent of vectors is for binary trees.
I am not sure what they are actually called so I can fix that.

Will put in a changelog entry if this is a wanted feature

### CODE REVIEW

**Comment by gallais** [comment]
Do you have a use case for it? You could write a `README.Data.Tree.Binary.Indexed`
explaining to users why one may want to use such a family.

**Comment by alexarice** [comment]
In the process of writing another pr which uses this, it should perhaps all be in one pr

**Comment by alexarice** [comment]
I think I'm going to close this until the whole thing is ready

**Comment by gallais** [comment]
Alternatively we have the not-ready-yet label.

**Pull request closed without merging**
