### PR TITLE
Purer `Data.Table`

### PR DESCRIPTION
**Pull request by bch29**
Continuing from #212.

> - Move swapFin from Data.Fin.Properties to Data.Fin, rename it swap and provide an explanation of what it does. It should be implemented via pattern matching instead of if_then_else_. This will then allow you to delete the if-dec-true and if-dec-false lemmas.
> - Move the swap-lem₁ and swap-lem₂ in Data.Fin.Properties out of public scope and give them more meaningful names.
> - Remove the permutation lemmas from Data.Fin.Properties from the PR

I've just removed all of these since I realised they're not actually used by any of the `Data.Table` code.

> - Move all the private lemmas in Data.Table (that do not rely on SigmaPropositional) into Data.Table.Properties as well as the proof of isomorphisms with Vec and Table.

I can't prove isomorphism with lists without `SigmaPropositional` so I've removed that proof entirely for now.

> - You seem to have carried out a find and replace for + to | in the changelog. Please can you fix this.

Ouch, I thought that bug in Spacemacs' markdown layer was fixed...

### CODE REVIEW

**Comment by MatthewDaggitt** [comment]
Awesome, thanks for all the work. Merging it in now.

**Comment by gallais** [comment]
Thanks a lot for this contribution!

**Comment by MatthewDaggitt** [comment]
@gallais  Hmm I've been playing around with this implementation today, and I have to say I'm not that convinced by encapsulating it in a record. It's particularly annoying when you want to pattern match on something that depends on the index of the new table. 

Consider definition of `select` in `Data.Table`. (ignore the pattern-matching of booleans). In order to access the index it's necessary to use postfix projections. This is something that:
- isn't commonly used in the standard library
- I imagine the average user will find it difficult to use
Do you have any thoughts?

I have to confess I'm kind of tempted to change the definition of `Table` back to
```agda
Table : ∀ {a} → Set a → ℕ → Set a
Table A n = Fin n → A
```
without the record type. Although it occasionally means you have to provide an extra argument to help type-inference, I think it greatly improves usability when defining your own tables.

@bch29 Sorry, this is one of the reasons why I wanted to take it slowly and put it in piece-by-piece! We want to truly make sure that the definitions are set up in the best way possible before piling everything on top of them. Don't worry, I'll do any rewriting of the existing implementation if we agree to change it.

By the way, given that you've now made a noteworthy contribution to the library, would you like us to add you to the [list of contributors](https://github.com/agda/agda-stdlib/blob/master/LICENCE)? If so, then under what name?

**Comment by bch29** [comment]
I've actually found it's a lot easier to do proofs by equational reasoning since making the change to a record type, since you don't have to worry any more about filling in the `n` parameter. I assumed things would get more difficult because of all the packing/unpacking, but it turns out that you never have to worry about that in proofs because Agda normalises past application of the record constructor really easily. You're right that defining table is a bit more difficult, though. Perhaps this kind of definition of `select` would be easy for the average user to write?

```agda
select : ∀ {n} {a} {A : Set a} → A → Fin n → Table A n → Table A n
select z i t = tabulate go
  where
  go : _ → _
  go j with ⌊ j ≟ i ⌋
  go j | false = lookup t i
  go j | true = z
```

**Comment by bch29** [comment]
@MatthewDaggitt yes it would be great to be added to the list of contributors, thanks. My name is Bradley Hardy.

**Comment by gallais** [comment]
Worth noticing that the definition of `select` does not have to be quite so verbose. E.g.

```agda
select : ∀ {n} {a} {A : Set a} → A → Fin n → Table A n → Table A n
lookup (select z i t) j with j ≟ i
... | yes _ = lookup t i
... | no _  = z
````

Or even, using `Function`'s `case_of_`:

```agda
select : ∀ {n} {a} {A : Set a} → A → Fin n → Table A n → Table A n
lookup (select z i t) j = case j ≟ i of λ where
  (yes _) → lookup t i
  (no _ ) → z
```

**Comment by bch29** [comment]
OK, I've never seen this `λ where` construct before, that's great! There's also the `if_then_else_` approach though, which I think is clearer. It's just that when you use helper functions like that it becomes slightly less clear how to prove things (hence the `if-dec-true` etc that appeared in my first PR). That being said, this magically goes through...

```agda
select : ∀ {n} {a} {A : Set a} → A → Fin n → Table A n → Table A n
select z i t = tabulate (λ j → if ⌊ j ≟ i ⌋ then lookup t i else z)

select-const : ∀ {n} {a} {A : Set a} (z : A) (i : Fin n) t → select z i t ≗ select z i (replicate (lookup t i))
select-const z i t j = P.refl
```

**Comment by gallais** [comment]
I guess at the moment we don't have e.g. `_++_` for which the record-wrapping should shine.

**Comment by MatthewDaggitt** [comment]
I'm pretty averse to adding `_++_` at all. I feel if you need concatenation then you should be using `Vec`!

Having said that I'll try porting my development to use the record implementation and report back...

**Pull request merged**
