### PR TITLE
Hide N argument in Tactic.RingSolver.NonReflective._⊜_

### LINKED ISSUE #1137: Tactic.RingSolver.NonReflective._⊜_ seems to have the wrong signature
Currently it looks like this:

```agda
_⊜_ : ∀ (n : ℕ) →
      Expr Carrier n →
      Expr Carrier n →
      Expr Carrier n × Expr Carrier n
_⊜_ _ = _,_
```

Surely it should look like this?

```agda
_⊜_ : ∀ {n : ℕ} →
      Expr Carrier n →
      Expr Carrier n →
      Expr Carrier n × Expr Carrier n
_⊜_ = _,_
```

### PR DESCRIPTION
**Pull request by dylanede**
Fixes #1137.

### CODE REVIEW

**Comment by dylanede** [comment]
@MatthewDaggitt

**Comment by MatthewDaggitt** [comment]
Thanks for the PR! Looks good to me. The only thing missing is a CHANGELOG entry, especially as this is a breaking change.

**Comment by MatthewDaggitt** [comment]
@dylanede any luck with a quick CHANGELOG entry on this? Just trying to avoid the fuss of me having to clone your entire fork 😄

**Comment by dylanede** [comment]
Ah, yeah, should be able to do that later today.

**Comment by gallais** [comment]
> Just trying to avoid the fuss of me having to clone your entire fork

Just FTR, you should be able to do something to the tune of:

```shell
git remote add dylanede https://github.com/dylanede/agda-stdlib
git fetch dylanede 1137
git checkout 1137
```

to get a local copy of the branch without pulling the whole clone.

That being said, I think it's sensible to ask contributors to input
CHANGELOG entries themselves: you have enough to deal with already! :D

**Comment by MatthewDaggitt** [comment]
> Just FTR, you should be able to do something to the tune of:

Ah neat, I hadn't come across that one before, thanks!

**Pull request merged**
