### PR TITLE
Added new modules Data.List.Categorical and Data.Vec.Categorical

### PR DESCRIPTION
**Pull request by MatthewDaggitt**
This new module groups together all the proofs that view Vec from a categorical perspective in one place. As an added bonus, the implicit module parameters allow the types of the proofs to be simplified into a more readable form.

Any comments?

### CODE REVIEW

**Comment by gallais** [comment]
Looks good to me. I'd use the opportunity to swap the `functor` and `applicative`
definitions as something needs to be a functor to begin with for it to make sense
to ask whether it's also an applicative.

**Comment by MatthewDaggitt** [comment]
> I'd use the opportunity to swap the functor and applicative

As in just swap their order in the file?

**Comment by MatthewDaggitt** [comment]
I've also created the analagous module `Data.List.Categorical` as we might as well do it properly. The contents is a bit of a mess, but no more of a mess than it was. Sorting it out can be done another day.

This also has the advantage of not terrifying new users to the library when they look in `Data.List` expecting to see some nice `map` and `fold` functions and instead get a terrifying page of `monads` and weird module skullduggery :smile: 

Also I've just emptied another `Data.X` file *sigh*

**Comment by gallais** [comment]
> As in just swap their order in the file?

Yep.

**Comment by MatthewDaggitt** [comment]
Thanks, I've swapped their ordering. I'm a little worried by the fact that such a dependency isn't enforced but anyway!

**Comment by andreasabel** [comment]
@sstucki : More work for you to update your Agda implementation of FInt. ;-)

**Comment by MatthewDaggitt** [comment]
> @sstucki : More work for you to update your Agda implementation of FInt. ;-)

@sstucki Apologies, if it does need some tidying up as a result of this. Having had a look through the repository, it should just involve changing a module reference at the top of a couple of files. The changes do significantly improve the layout and dependencies in the library, promise!

**Comment by sstucki** [comment]
@andreasabel, @MatthewDaggitt, thanks for the heads up.

I went through my code and updated it to the latest version of the stdlib, and the changes caused by this were indeed minimal. The imports look better now too, so thanks :-)

There was one regression due to the removal of All₂ from Data.Vec.All in 81fc9c6, and I filed a corresponding PR: #209

**Pull request merged**
