### PR TITLE
Deprivatised properties in Data.Nat

### PR DESCRIPTION
**Pull request by MatthewDaggitt**
Moved useful lemmas and properties in the Data.Nat file that were previously in private scope, either explicitly or within records, into public scope.

### CODE REVIEW

**Comment by MatthewDaggitt** [comment]
Accidentally closed, reopening.

**Comment by andreasabel** [comment]
I wonder whether these properties would find a better home in Data.Nat.Properties or Data.Nat.Properties.Simple.  Have you also investigated these alternatives?

**Comment by MatthewDaggitt** [comment]
I completely agree! In fact there was some discussion about it in the now-closed original pull request (https://github.com/agda/agda-stdlib/pull/90). 

Unfortunately I have made a terrible mess of this trying to rebase it with the latest updates. Unless anyone knows how to fix it, I think I'm going to have to create a new pull request (with the suggestions included).

**Comment by MatthewDaggitt** [comment]
Actually before I start on it, it would probably save a lot of time if the deprivatising Data.Nat.Properties pull request (https://github.com/agda/agda-stdlib/pull/102) could be accepted first. Assuming there are no problems with it?

**Comment by asr** [comment]
I guess you can

1. Create a *new* branch from the current master
2. Cherry-pick the commits from the deprivatising-DataNaT branch
3. Create a *new* PR using the *new* branch

**Comment by MatthewDaggitt** [comment]
@asr Yes, sounds like the best plan.

**Comment by MatthewDaggitt** [comment]
A fresh version can be found in pull request https://github.com/agda/agda-stdlib/pull/129

**Pull request closed without merging**
