### PR TITLE
 Fix link to source in html for 2.4.2.1

### PR DESCRIPTION
**Pull request by jdnavarro**
Hope it's alright now.

### CODE REVIEW

**Comment by asr** [comment]
Merging...

**Comment by asr** [comment]
I have no problems merging your pull request in the 2.4.2.1 branch, but in the master branch I have a merge conflict in the .travis.yml file. I don't understand it.

Testing...

**Comment by jdnavarro** [comment]
How are you merging in `master`? I think a direct merge with `master` and my `patch-2` branch will include *all* differences between `master` and `2.4.2.1`, and you surely don't want that. Instead you could cherry pick just my latest commit from `patch-2` into `master` or you can you directly merge from my `patch-1` branch which is based in `master`.

**Comment by asr** [comment]
Thanks, I cherry-picked the commit.

**Pull request merged**
