### PR TITLE
[ new ] Data.Trie(.NonEmpty)

### PR DESCRIPTION
**Pull request by gallais**
This provides a nice use-case for `Data.These`: we have either a
value, a non-empty tree of sub-tries, or both!

### CODE REVIEW

**Comment by MatthewDaggitt** [comment]
Hmm so before we add this is in, I think we probably need to have a discussion about how we're going to incorporate sized data in general? Presumably at some point we'll be adding sized nats, lists etc. as well. Any ideas about where these are going to fit in the existing hierarchy?

**Comment by gallais** [comment]
> Presumably at some point we'll be adding sized nats, lists etc. as well.

I don't know. So far I have only found sizes to be useful for *nested* datatypes because
we typically want to traverse them using a higher-order function. The level of indirection
introduced by this higher-order function prevents Agda's termination checker from
seeing that all the calls are benign. Sizes solve that.

In the current stdlib, I think would only want indices in [`Data.W`](https://agda.github.io/agda-stdlib/Data.W.html) because that would
enable us to use `map` for `Container` when definition `map` for `W` (which we can do
for [`Codata.M`](https://agda.github.io/agda-stdlib/Codata.M.html#814) thanks to sizes).

**Comment by MatthewDaggitt** [comment]
Hmm okay. Another couple of possibly naive questions then. 
- Will the same data type ever need different sizing schemes for different higher order functions?
- Do we want a sized and a non-sized version of `Trie`?

**Comment by gallais** [comment]
> Will the same data type ever need different sizing schemes for different higher order functions?

Here's a simplified picture with explicit sizes:
```agda
map : {V W : Set} -> (V -> W) -> F V -> F W -- knows nothing about sizes
map = (...)

data T (i : Size) : Set where
  node : (j : Size< i) -> F (T j) -> T i -- pretend it's strictly positive

fold : (i : Size) (alg : F A -> A) -> T i -> A
fold i alg (node j t) =
     -- v `map` here has type `(T j -> A) -> F (T j) -> F A`
     --    despite not caring about sizes
  alg $ map (fold j alg) t
          -- ^ `fold` is only partially applied but obviously (thanks to the sizes)
          -- called at a smaller argument
```

Without sizes we would need to inline a specialized version of `map` mutually defined
with `fold` to get the same behaviour.


> Do we want a sized and a non-sized version of Trie?

We are effectively doing that when we pick the size `∞`: all of the sub-Tries also
have size `∞`.

**Comment by gallais** [comment]
Should this be called `Data.Trie.NonEmpty`? `Data.Trie` could be the `Maybe`-wrapped
version of this and provide functions properly handling the special case of the empty Trie.

**Comment by gallais** [comment]
Same here: cyclic dependency between these and Maybe.
Maybe all of these should go in the `Data.Maybe.Base` module.


```agda
-- Deletion

  deleteThis : These A B → Maybe (These A B)
  deleteThis = fold (const nothing) (just ∘′ that) (const (just ∘′ that))

  deleteThat : These A B → Maybe (These A B)
  deleteThat = fold (just ∘′ this) (const nothing) (const ∘′ just ∘′ this)

-- Component extraction via Maybe

  fromThis : These A B → Maybe A
  fromThis = fold just (const nothing) (const ∘′ just)

  fromThat : These A B → Maybe B
  fromThat = fold (const nothing) just (const just)
```

**Comment by gallais** [comment]
I'm going to look into whether we can relax the constraint that values in a trie
need to correspond to keys relying on propositional equality.

**Comment by gallais** [comment]
I now have a concrete use-case for this. I'll add it as README doc.

**Comment by MatthewDaggitt** [comment]
I've updated this to work with v1.0. Sorry still got another question! Why is the mysterious explicit parameter `v : Level` needed everywhere? Don't we know that the data in the tree is always going to be of type `Carrier` from the `StrictTotalOrder` so why do we parameterise over an extra level?

**Comment by gallais** [comment]
Thanks for the cleanup.

When I was trying to get `Trie` to work with the setoid of keys, I somehow convinced
myself that the values needed to live somewhere above `k ⊔ e ⊔ r` hence taking a
`v` and demanding that the values live in `v ⊔ k ⊔ e ⊔ r`. Turns out it's not needed.

So I've removed that, dropped the explicit level (which can now be inferred from
the `Value v` argument) and I have cleaned-up `Data.Trie` following what you did
for `Data.Trie.NonEmpty`.

Also fixed a bug (`toList` in `Data.Trie` was taking a non-empty `Trie⁺` instead of
a `Trie`).

**Comment by gallais** [comment]
IIRC splitting `Data.These` to introduce `Data.These.Base` may conflict with a
refactoring you did that puts some of `Data.These`'s function in `Data.Maybe.Base`.
I'll check that we don't have duplicated definitions before switching back to "ready".

**Comment by MatthewDaggitt** [comment]
That's great, looks much cleaner. 

Okay next question, sorry! The `Trie` currently takes an argument of type `Value v`. If I understand it correctly, `Value` is a wrapper class for an indexed set equipped with a proof that the indexing respects the equality over the keys.

My question is do we need indexed sets for a trie? You're not using it in your Lexer example as you're passing the `const` function right? If not can't we just pass a `Set` instead of a `Value`? Now I think about it `Data.AVL` probably shouldn't use `Value` in it's public interface?

Anyway if we keep it, it should probably be explained in the `README` what the `Value` does...

**Comment by gallais** [comment]
I was going to add an example of a trie grouping anagrams where:

* the paths are assumed to be in increasing order
* the leaves contain list of words which are proven to be permutations of the paths
  leading to them

However because of #713 I can't write it down right now. :D

**Comment by MatthewDaggitt** [comment]
Merged in, got to have been near a record for the longest open PR. Once again apologies for all my questions :smile:

**Pull request merged**
