### PR TITLE
Fixity

### PR DESCRIPTION
**Pull request by JacquesCarette**
A tiny part of issue #207 (about 15% of the missing cases done).

### CODE REVIEW

**Comment by MatthewDaggitt** [comment]
Nice! I particularly like the README file :+1: 

You're going to hate me for this, but each of these probably need a changelog entry (particularly as these are breaking changes)

**Comment by JacquesCarette** [comment]
Oh my, CHANGELOG entries. That does increase the workload too.  Oh well, I'll work on plowing through that as well.

**Comment by gallais** [comment]
:heart:

**Comment by MatthewDaggitt** [comment]
> Oh my, CHANGELOG entries. That does increase the workload too. Oh well, I'll work on plowing through that as well.

Apologies... You could add them in for these changes, and then I can merge this lot in as is. That way you don't have to do the whole thing in one go?

**Comment by JacquesCarette** [comment]
That was my plan, otherwise there's just too much. I just haven't had the time to circle back.

**Pull request merged**
