### PR TITLE
[ new ] proofs: All & operations constructing lists

### PR DESCRIPTION
**Pull request by gallais**

### CODE REVIEW

**Comment by MatthewDaggitt** [comment]
My only concern is the name `[]⁻` to me this looks we're reasoning about the empty list. Maybe `[x]⁻` instead? Or `[-]⁻`?

**Comment by gallais** [comment]
What about `singleton⁻`?

**Comment by MatthewDaggitt** [comment]
Yup, that'd work!

**Comment by gallais** [comment]
Consider it done!

**Pull request merged**
