### PR TITLE
Proofs about `_/_`

### PR DESCRIPTION
**Pull request by MatthewDaggitt**
First serious attempt at adding some non-trivial proofs for `_/_` which are needed for the upcoming refactor of LCM. In the process I needed to move the definition of divisibility into it's own module `Divisibility.Core` so it can be used in `DivMod`, and I also fixed a naming bug in `Data.Nat.Properties`.

The `divₕ-offsetEq` lemma is officially my new least favourite proof in the library :smile:

### CODE REVIEW

**Comment by JacquesCarette** [comment]
I agree, the proof of `divₕ-offsetEq` is quite the monster. I was curious to see if I could help, but ran into an issue I never was able to figure out: where to find the sources of the `Agda.Builtin.*` (in this case, `Nat`) to find the definition of `divₕ-helper`.

**Comment by gallais** [comment]
On my laptop they're in `.cabal/share/x86_64-linux-ghc-8.4.4/Agda-2.6.0/lib/prim`.
However the easiest way is to open `Data.Nat.Base` and click on `Agda.Builtin.Nat`
to get there in emacs.

**Comment by JacquesCarette** [comment]
I'm still curious to know where the sources for those live, on either agda/agda or agda/agda-stdlib.

**Comment by gallais** [comment]
Ah sorry, I did not understant that this was your question.
You can find the `Agda.Builtin.X` modules in agda/agda in the [`src/data/lib/prim/`](https://github.com/agda/agda/tree/master/src/data/lib/prim/) directory.

**Comment by MatthewDaggitt** [comment]
@JacquesCarette I'm going to merge this in, as it's blocking some more upcoming PRs. Please do feel free to continue to hack around with `divₕ-offsetEq` if you like.

**Pull request merged**
