### PR TITLE
[fix] issue #1864

### PR DESCRIPTION
**Pull request by jamesmckinna**

### CODE REVIEW

**Comment by MatthewDaggitt** [comment]
So what was the actual problem here?

**Comment by jamesmckinna** [comment]
See the issue #1864. The 'problem' you had identified was the `import`s being too heavy, so i thinned them out. But while I was doing that, I also saw that the structure of what is actually there is a lot of highly repetitive code for conjuring a decidable relation on a product out of decidable relations on its components. And that seems worth thinking about trying to refactor. So the PR as it stands/stood closed the original issue (as I understood it), while leaving the issue open with more work potentially to do... does that make sense?

**Comment by MatthewDaggitt** [comment]
Yes, sorry, that was too terse of me! I meant what was actually the concrete `import` that caused the dependency cycles! But if you didn't identify it and just removed all that you could, that is also fine!

> So the PR as it stands/stood closed the original issue (as I understood it), while leaving the issue open with more work potentially to do... does that make sense?

:+1:

**Comment by jamesmckinna** [comment]
yes, i didn't do the analysis... except by the tried-and-true-but-brainless method of commenting out imports, and only reinstating locally the actual functions needing to be imported. But quite a lot, it seemed, could simply be deleted...

**Comment by MatthewDaggitt** [comment]
> BTW, I never saw dependency cycles as such, so i wonder if that was a problem at your end?

No, I never saw dependency cycles, apologies if I wrote that. Its just that I was type-checking them and it was ending up type-checking half the standard library in order to do so. Which wasn't exactly great for code needed for writing tactics.

**Pull request merged**
