### PR TITLE
[ new ] pretty printing of binary trees

### PR DESCRIPTION
**Pull request by gallais**
Question: should we move `toRose` out of `Data.Tree.Binary` because it requires
the addition of the `--sized-types` option? And if so: where?

### CODE REVIEW

**Comment by MatthewDaggitt** [comment]
> Question: should we move toRose out of Data.Tree.Binary because it requires
the addition of the --sized-types option? And if so: where?

Hmm I agree the pollution of all the modules with `--sized-types` is unpleasant and could potentially get a lot worse.
- One option would be to rename it `fromBinary` and move it to `Data.Tree.Rose`. The downside is that rose trees are the most general type of tree so it seems a bit backwards to have it depend on the other types.
- Alternatively we could move it to a new module `Data.Tree.Binary.Conversion`? See #1033 in which I propose `Data.Fin.Conversion`...

**Comment by MatthewDaggitt** [comment]
Also another more general question that has just occurred to me is that we have `Data.(Bool/Nat/Integer/Rational).Show` modules which feel like they have significant overlap with the new `Text` hierarchy. How should we resolve these?

To be honest I feel like we should stick with the `Show` modules as in general the pattern we're moving towards has been to keep everything local to the data-type within it's own folder, e.g. we would rename `Text.Tree.Binary.Linear` to `Data.Tree.Binary.Show` or `Data.Tree.Binary.Show.Linear`?

**Comment by MatthewDaggitt** [comment]
Brought this back up-to-date and moved `toRose` to `fromBinary` to get rid of the sized type issues and moved `Text.Tree.Linear` to `Data.Tree.X.Show`. @gallais any thoughts?

**Comment by gallais** [comment]
Looks good to me! Sorry I completely forgot about this PR.

**Pull request merged**
