### PR TITLE
getLine to PrimIO and getLine∞ to IO

### PR DESCRIPTION
**Pull request by mpkh**
``` agda
main' : IO ⊤
main' = ♯ getLine∞ >>= (λ x → ♯ (putStrLn∞ x))

main : Prim.IO ⊤
main = run main'
```

### CODE REVIEW

**Comment by MatthewDaggitt** [comment]
Looks reasonable to add. Does anyone know how to update to use the new style `{-# COMPILE GHC ... }` pragmas?

**Comment by gallais** [comment]
Shouldn't a line be, by definition, finite?

**Comment by mpkh** [comment]
@MatthewDaggitt @gallais  it's from 2014, I will be glad if that will be corrected and merged but afair that's pointless for current agda's purposes

**Comment by UlfNorell** [comment]
> Does anyone know how to update to use the new style {-# COMPILE GHC ... } pragmas?

http://agda.readthedocs.io/en/latest/language/foreign-function-interface.html#compiler-pragmas

**Comment by MatthewDaggitt** [comment]
Closing due to a combination of age, outdated code and a lack of knowledge on my part on how to fix/test it. If anyone feels strongly about this particular functionality, feel free to reopen it with an updated patch.

**Pull request closed without merging**
