### PR TITLE
Data.Nat.Properties: Add more properties

### PR DESCRIPTION
**Pull request by alexarice**
Adds some missing properties for <= triple prime

### CODE REVIEW

**Comment by MatthewDaggitt** [comment]
Looks good to me! Any chance you could add a CHANGELOG entry?

**Comment by alexarice** [comment]
Sure, I'll get that done later

**Comment by alexarice** [comment]
Done :)

**Comment by MatthewDaggitt** [comment]
Thanks, I'll leave it up for a couple of days to see if anyone else has any comments, and then I'll merge it in.

**Pull request merged**
